package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"turtle/graph/model"
	"turtle/internal/domain"
	"turtle/internal/domain/aggregates"
	"turtle/internal/domain/valueobjects"
	pkgErrors "turtle/pkg/errors"

	"github.com/google/uuid"
)

// CreateAddress creates a new address
func (r *mutationResolver) CreateAddress(ctx context.Context, input model.CreateAddressInput) (*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Create location
	location, err := valueobjects.NewLocation(input.Location.Latitude, input.Location.Longitude)
	if err != nil {
		return nil, handleError(ctx, pkgErrors.ErrInvalidInput("location", err.Error()))
	}

	// Handle label - it's a pointer because it has a default value in GraphQL
	label := model.AddressLabelOther // default
	if input.Label != nil {
		label = *input.Label
	}

	// Create address aggregate
	address, err := aggregates.NewAddress(
		uuid.New().String(),
		userID,
		addressLabelToDomain(label), // Now passing the dereferenced value
		input.AddressLine1,
		stringValue(input.AddressLine2),
		stringValue(input.Landmark),
		input.City,
		input.State,
		stringValue(input.Country),
		stringValue(input.PostalCode),
		location,
		stringValue(input.ContactName),
		stringValue(input.ContactPhone),
	)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Set as default if requested
	if boolValue(input.SetAsDefault) {
		address.SetAsDefault()
	}

	// Save address
	err = r.Resolver.addressService.CreateAddress(ctx, userID, address)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return addressToGraphQL(address), nil
}

// UpdateAddress updates an existing address
func (r *mutationResolver) UpdateAddress(ctx context.Context, input model.UpdateAddressInput) (*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Fetch address
	address, err := r.Resolver.addressService.GetAddress(ctx, input.ID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Verify ownership
	if address.UserID() != userID {
		return nil, pkgErrors.ErrForbidden("You don't have permission to update this address")
	}

	// Create location if provided
	var location *valueobjects.Location
	if input.Location != nil {
		location, err = valueobjects.NewLocation(input.Location.Latitude, input.Location.Longitude)
		if err != nil {
			return nil, pkgErrors.ErrInvalidInput("location", err.Error())
		}
	} else {
		location = address.Location()
	}

	// Get values with fallback to existing
	label := address.Label()
	if input.Label != nil {
		label = addressLabelToDomain(*input.Label)
	}

	addressLine1 := address.AddressLine1()
	if input.AddressLine1 != nil {
		addressLine1 = *input.AddressLine1
	}

	city := address.City()
	if input.City != nil {
		city = *input.City
	}

	state := address.State()
	if input.State != nil {
		state = *input.State
	}

	postalCode := address.PostalCode()
	if input.PostalCode != nil {
		postalCode = stringValue(input.PostalCode)
	}

	// Update address
	err = address.Update(
		label,
		addressLine1,
		stringValue(input.AddressLine2),
		stringValue(input.Landmark),
		city,
		state,
		postalCode,
		location,
		stringValue(input.ContactName),
		stringValue(input.ContactPhone),
	)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Save changes
	updatedAddress, err := r.Resolver.addressService.UpdateAddress(ctx, userID, address)

	return addressToGraphQL(updatedAddress), nil
}

// DeleteAddress soft deletes an address
func (r *mutationResolver) DeleteAddress(ctx context.Context, id string) (bool, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return false, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Delete address
	err := r.Resolver.addressService.DeleteAddress(ctx, userID, id)
	if err != nil {
		return false, handleError(ctx, err)
	}

	return true, nil
}

// SetDefaultAddress sets an address as default
func (r *mutationResolver) SetDefaultAddress(ctx context.Context, id string) (*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Use service - it handles unset, update, and cache management
	updatedAddress, err := r.Resolver.addressService.SetDefaultAddress(ctx, userID, id)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return addressToGraphQL(updatedAddress), nil
}

// VerifyAddress marks an address location as verified
func (r *mutationResolver) VerifyAddress(ctx context.Context, id string) (*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	updatedAddress, err := r.Resolver.addressService.VerifyAddress(ctx, userID, id)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return addressToGraphQL(updatedAddress), nil
}

// Address returns address by ID
func (r *queryResolver) Address(ctx context.Context, id string) (*model.Address, error) {
	address, err := r.Resolver.addressService.GetAddress(ctx, id)
	if err != nil {
		if err == domain.ErrNotFound {
			return nil, nil
		}
		return nil, handleError(ctx, err)
	}

	return addressToGraphQL(address), nil
}

// MyAddresses returns all addresses for current user
func (r *queryResolver) MyAddresses(ctx context.Context) ([]*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	addresses, err := r.Resolver.addressService.GetUserAddresses(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	result := make([]*model.Address, len(addresses))
	for i, addr := range addresses {
		result[i] = addressToGraphQL(addr)
	}

	return result, nil
}

// MyDefaultAddress returns the default address for current user
func (r *queryResolver) MyDefaultAddress(ctx context.Context) (*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Get all addresses and find the default one
	addresses, err := r.Resolver.addressService.GetUserAddresses(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Find default address
	for _, addr := range addresses {
		if addr.IsDefault() {
			return addressToGraphQL(addr), nil
		}
	}

	// No default address found
	return nil, nil
}

// SuggestedAddresses returns smart address suggestions
func (r *queryResolver) SuggestedAddresses(ctx context.Context, limit *int) ([]*model.AddressSuggestion, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	l := 3 // Default limit
	if limit != nil {
		l = *limit
	}

	addresses, err := r.Resolver.addressService.GetSuggestedAddresses(ctx, userID, l)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Convert to AddressSuggestion type
	result := make([]*model.AddressSuggestion, len(addresses))
	for i, addr := range addresses {
		result[i] = &model.AddressSuggestion{
			Address: addressToGraphQL(addr),
			Score:   r.Resolver.addressService.CalculateConfidence(addr), // Simple scoring based on usage
			Reason:  r.Resolver.addressService.GenerateSuggestionReason(addr),
		}
	}

	return result, nil
}

// NearestAddresses returns addresses near a location
func (r *queryResolver) NearestAddresses(ctx context.Context, latitude float64, longitude float64, limit *int) ([]*model.Address, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	l := 5 // Default limit
	if limit != nil {
		l = *limit
	}

	addresses, err := r.Resolver.addressService.FindNearestAddresses(ctx, userID, latitude, longitude, l)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	result := make([]*model.Address, len(addresses))
	for i, addr := range addresses {
		result[i] = addressToGraphQL(addr)
	}

	return result, nil
}

// SearchAddresses searches user's addresses
func (r *queryResolver) SearchAddresses(ctx context.Context, input model.AddressSearchInput) (*model.AddressConnection, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Extract search parameters with defaults
	query := ""
	if input.Query != nil {
		query = *input.Query
	}

	l := 20
	if input.Limit != nil {
		l = *input.Limit
	}

	o := 0
	if input.Offset != nil {
		o = *input.Offset
	}

	addresses, total, err := r.Resolver.addressService.SearchAddresses(ctx, userID, query, l, o)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	edges := make([]*model.AddressEdge, len(addresses))
	for i, addr := range addresses {
		edges[i] = &model.AddressEdge{
			Cursor: fmt.Sprintf("%d", o+i),
			Node:   addressToGraphQL(addr),
		}
	}

	return &model.AddressConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     int64(o+l) < total,
			HasPreviousPage: o > 0,
			Total:           int(total),
		},
		TotalCount: int(total),
	}, nil
}

// AddressStats returns address statistics
func (r *queryResolver) AddressStats(ctx context.Context) (*model.AddressStats, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	stats, err := r.Resolver.addressService.GetAddressStats(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return &model.AddressStats{
		TotalAddresses:  int(stats.TotalAddresses),
		MostUsedAddress: addressToGraphQL(stats.MostUsedAddress),
		DefaultAddress:  addressToGraphQL(stats.DefaultAddress),
		RecentAddresses: addressesToGraphQL(stats.RecentAddresses),
	}, nil
}
