package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
	"turtle/services/address"
)

// ID is the resolver for the id field.
func (r *addressResolver) ID(ctx context.Context, obj *models.Address) (int, error) {
	return int(obj.ID), nil
}

// UserID is the resolver for the userId field.
func (r *addressResolver) UserID(ctx context.Context, obj *models.Address) (int, error) {
	return int(obj.UserID), nil
}

// Label converts database string to GraphQL enum
// This is called automatically by GraphQL when the label field is requested
func (r *addressResolver) Label(ctx context.Context, obj *models.Address) (*model.AddressLabel, error) {
	if obj.Label == "" {
		return nil, nil
	}
	label := model.AddressLabel(obj.Label)
	return &label, nil
}

// PreferredTimeSlot is the resolver for the preferredTimeSlot field.
func (r *addressResolver) PreferredTimeSlot(ctx context.Context, obj *models.Address) (*model.TimeOfDay, error) {
	slot := obj.GetPreferredTimeSlot()
	timeOfDay := model.TimeOfDay(slot)
	return &timeOfDay, nil
}

// CreateAddress is the resolver for the createAddress field.
func (r *mutationResolver) CreateAddress(ctx context.Context, input model.CreateAddressInput) (*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	addressInput := address.CreateAddressInput{
		UserID:       authUser.UserID,
		Label:        addressLabelToString(input.Label),
		AddressLine1: input.AddressLine1,
		AddressLine2: ptrToString(input.AddressLine2),
		Landmark:     ptrToString(input.Landmark),
		City:         input.City,
		State:        input.State,
		Country:      ptrToString(input.Country),
		PostalCode:   input.PostalCode,
		Latitude:     input.Latitude,
		Longitude:    input.Longitude,
		ContactName:  ptrToString(input.ContactName),
		ContactPhone: ptrToString(input.ContactPhone),
		IsDefault:    ptrToBool(input.IsDefault),
	}

	addr, err := r.Resolver.AddressService.CreateAddress(addressInput)
	if err != nil {
		return nil, err
	}

	return addr, nil
}

// UpdateAddress is the resolver for the updateAddress field.
func (r *mutationResolver) UpdateAddress(ctx context.Context, id int, input model.UpdateAddressInput) (*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	updateInput := address.UpdateAddressInput{
		Label:        stringPtr(enumToString(input.Label)),
		AddressLine1: input.AddressLine1,
		AddressLine2: input.AddressLine2,
		Landmark:     input.Landmark,
		City:         input.City,
		State:        input.State,
		PostalCode:   input.PostalCode,
		Latitude:     input.Latitude,
		Longitude:    input.Longitude,
		ContactName:  input.ContactName,
		ContactPhone: input.ContactPhone,
		IsActive:     input.IsActive,
	}

	addr, err := r.Resolver.AddressService.UpdateAddress(uint(id), authUser.UserID, updateInput)
	if err != nil {
		return nil, err
	}

	return addr, nil
}

// DeleteAddress is the resolver for the deleteAddress field.
func (r *mutationResolver) DeleteAddress(ctx context.Context, id int) (*model.SuccessResponse, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.Resolver.AddressService.DeleteAddress(uint(id), authUser.UserID); err != nil {
		return &model.SuccessResponse{
			Success: false,
			Message: stringPtr("Failed to delete address"),
		}, err
	}

	return &model.SuccessResponse{
		Success: true,
		Message: stringPtr("Address deleted successfully"),
	}, nil
}

// SetDefaultAddress is the resolver for the setDefaultAddress field.
func (r *mutationResolver) SetDefaultAddress(ctx context.Context, id int) (*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	addr, err := r.Resolver.AddressService.SetDefaultAddress(uint(id), authUser.UserID)
	if err != nil {
		return nil, err
	}

	return addr, nil
}

// VerifyAddress is the resolver for the verifyAddress field.
func (r *mutationResolver) VerifyAddress(ctx context.Context, id int) (*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	addr, err := r.Resolver.AddressService.VerifyAddress(uint(id), authUser.UserID)
	if err != nil {
		return nil, err
	}

	return addr, nil
}

// Queries
// MyAddresses is the resolver for the myAddresses field.
func (r *queryResolver) MyAddresses(ctx context.Context) ([]*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	addresses, err := r.Resolver.AddressService.GetUserAddresses(authUser.UserID)
	if err != nil {
		return nil, err
	}

	return addresses, nil
}

// Address is the resolver for the address field.
func (r *queryResolver) Address(ctx context.Context, id int) (*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	address, err := r.Resolver.AddressService.GetAddressByID(uint(id))
	if err != nil {
		return nil, err
	}

	// Check authorization
	if address.UserID != authUser.UserID {
		return nil, middlewares.ErrUnauthorized
	}

	return address, nil
}

// DefaultAddress is the resolver for the defaultAddress field.
func (r *queryResolver) DefaultAddress(ctx context.Context) (*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	address, err := r.Resolver.AddressService.GetDefaultAddress(authUser.UserID)
	if err != nil {
		return nil, err
	}

	return address, nil
}

// SuggestedAddresses is the resolver for the suggestedAddresses field.
func (r *queryResolver) SuggestedAddresses(ctx context.Context, timeOfDay *model.TimeOfDay) ([]*models.Address, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	timeSlot := "MORNING"
	if timeOfDay != nil {
		timeSlot = string(*timeOfDay)
	}

	addresses, err := r.Resolver.AddressService.GetSuggestedAddresses(authUser.UserID, timeSlot)
	if err != nil {
		return nil, err
	}

	return addresses, nil
}

// Address returns generated.AddressResolver implementation.
func (r *Resolver) Address() generated.AddressResolver { return &addressResolver{r} }

type addressResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *addressResolver) FullAddress(ctx context.Context, obj *models.Address) (string, error) {
	return obj.GetFullAddress(), nil
}
*/
