package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"
	"turtle/graph/model"
	"turtle/internal/application/usecases"
	"turtle/internal/domain"
	"turtle/internal/domain/aggregates"
	pkgErrors "turtle/pkg/errors"
	"turtle/pkg/jwt"
)

// SocialLogin handles Google/Apple login for customers
func (r *mutationResolver) SocialLogin(ctx context.Context, input model.SocialLoginInput) (*model.AuthResponse, error) {
	// Convert GraphQL input to service input
	serviceInput := usecases.SocialLoginInput{
		Provider:   string(input.Provider),
		ProviderID: input.ProviderID,
		Email:      input.Email,
		FirstName:  input.FirstName,
		LastName:   input.LastName,
		ProfilePic: stringValue(input.ProfilePic),
		DeviceType: string(input.DeviceType),
		DeviceInfo: input.DeviceInfo,
	}

	// Call authentication service
	output, err := r.Resolver.authService.SocialLogin(ctx, serviceInput)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Fetch full user details
	user, err := r.Resolver.userRepo.FindByID(ctx, output.UserID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Convert to GraphQL response
	return &model.AuthResponse{
		Tokens: &model.AuthToken{
			AccessToken:  output.AccessToken,
			RefreshToken: output.RefreshToken,
			ExpiresAt:    output.ExpiresAt,
			TokenType:    "Bearer",
		},
		User:       userToGraphQL(user),
		IsNewUser:  output.IsNewUser,
		NeedsPhone: boolPtr(output.NeedsPhone),
	}, nil
}

// RequestOtp sends OTP to phone number
func (r *mutationResolver) RequestOtp(ctx context.Context, input model.RequestOTPInput) (*model.OTPResponse, error) {
	serviceInput := usecases.SendOTPInput{
		Phone:   input.Phone,
		Purpose: string(input.Purpose),
	}

	err := r.Resolver.authService.SendOTP(ctx, serviceInput)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return &model.OTPResponse{
		Success:   true,
		Message:   "OTP sent successfully",
		Target:    input.Phone,
		ExpiresAt: time.Now().Add(15 * time.Minute),
	}, nil
}

// VerifyOtp is the resolver for the verifyOTP field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, input model.VerifyOTPInput) (*model.AuthResponse, error) {
	serviceInput := usecases.VerifyOTPInput{
		Phone:      input.Phone,
		Code:       input.Code,
		Purpose:    string(input.Purpose),
		DeviceType: string(input.DeviceType),
		DeviceInfo: input.DeviceInfo,
	}

	output, err := r.Resolver.authService.VerifyOTPAndLogin(ctx, serviceInput)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Fetch full user details
	user, err := r.Resolver.userRepo.FindByID(ctx, output.UserID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Check if KYC needed
	needsKYC := false
	if user.IsCaptain() && user.CaptainProfile() != nil {
		needsKYC = user.CaptainProfile().KYCStatus() != aggregates.KYCVerified
	}

	return &model.AuthResponse{
		Tokens: &model.AuthToken{
			AccessToken:  output.AccessToken,
			RefreshToken: output.RefreshToken,
			ExpiresAt:    output.ExpiresAt,
			TokenType:    "Bearer",
		},
		User:      userToGraphQL(user),
		IsNewUser: output.IsNewUser,
		NeedsKyc:  boolPtr(needsKYC),
	}, nil
}

// RefreshToken refreshes access token
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (*model.AuthToken, error) {
	tokenPair, err := r.Resolver.authService.RefreshAccessToken(ctx, input.RefreshToken)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return &model.AuthToken{
		AccessToken:  tokenPair.AccessToken,
		RefreshToken: tokenPair.RefreshToken,
		ExpiresAt:    tokenPair.ExpiresAt,
		TokenType:    "Bearer",
	}, nil
}

// Logout revokes current session
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// Get refresh token from context (set by auth middleware)
	refreshToken, err := getRefreshTokenFromContext(ctx)
	if err != nil {
		return false, pkgErrors.ErrUnauthorized("No active session")
	}

	logErr := r.Resolver.authService.Logout(ctx, refreshToken)
	if logErr != nil {
		return false, handleError(ctx, logErr)
	}

	return true, nil
}

// LogoutAll revokes all sessions for user
func (r *mutationResolver) LogoutAll(ctx context.Context) (bool, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return false, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	err := r.Resolver.refreshTokenRepo.RevokeAllForUser(ctx, userID)
	if err != nil {
		return false, handleError(ctx, err)
	}

	return true, nil
}

// AddPhone adds phone number to customer account
func (r *mutationResolver) AddPhone(ctx context.Context, input model.AddPhoneInput) (*model.OTPResponse, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	serviceInput := usecases.AddPhoneNumberInput{
		UserID: userID,
		Phone:  input.Phone,
	}

	err := r.Resolver.authService.AddPhoneNumber(ctx, serviceInput)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return &model.OTPResponse{
		Success:   true,
		Message:   "Verification OTP sent to phone",
		Target:    input.Phone,
		ExpiresAt: time.Now().Add(15 * time.Minute),
	}, nil
}

// VerifyPhone verifies added phone number
func (r *mutationResolver) VerifyPhone(ctx context.Context, input model.VerifyPhoneInput) (bool, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return false, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	serviceInput := usecases.VerifyPhoneInput{
		UserID: userID,
		Phone:  input.Phone,
		Code:   input.Code,
	}

	err := r.Resolver.authService.VerifyPhone(ctx, serviceInput)
	if err != nil {
		return false, handleError(ctx, err)
	}

	return true, nil
}

// BecomeCaptain converts customer to captain
func (r *mutationResolver) BecomeCaptain(ctx context.Context, input model.BecomeCaptainInput) (*model.User, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	serviceInput := usecases.BecomeCaptainInput{
		UserID: userID,
		Phone:  stringValue(input.Phone),
	}

	output, err := r.Resolver.authService.BecomeCaptain(ctx, serviceInput)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	if !output.Success {
		return nil, fmt.Errorf("%s", output.Message)
	}

	// Fetch updated user
	user, err := r.Resolver.userRepo.FindByID(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(user), nil
}

// Me returns current authenticated user
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, nil
	}

	user, err := r.Resolver.userRepo.FindByID(ctx, userID)
	if err != nil {
		if err == domain.ErrNotFound {
			return nil, nil
		}
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(user), nil
}

// MySessions returns all active sessions
func (r *queryResolver) MySessions(ctx context.Context) ([]*model.Session, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	tokens, err := r.Resolver.refreshTokenRepo.FindActiveByUserID(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	sessions := make([]*model.Session, len(tokens))
	for i, token := range tokens {
		sessions[i] = &model.Session{
			ID:         fmt.Sprintf("%d", token.ID),
			Device:     model.DeviceType(token.Device),
			DeviceInfo: token.DeviceInfo,
			LastUsedAt: TimeValue(token.LastUsedAt),
			CreatedAt:  token.CreatedAt,
			ExpiresAt:  token.ExpiresAt,
			IsActive:   !token.IsRevoked && time.Now().Before(token.ExpiresAt),
		}
	}

	return sessions, nil
}

// VerifyToken checks if token is valid
func (r *queryResolver) VerifyToken(ctx context.Context, token string) (bool, error) {
	_, err := jwt.VerifyToken(token)
	return err == nil, nil
}
