package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"

	"turtle/db"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
	"turtle/pkg/jwt"
	"turtle/services/auth"
	"turtle/services/otp"
)

// SocialLogin is the resolver for the socialLogin field.
func (r *mutationResolver) SocialLogin(ctx context.Context, provider model.Provider, providerToken string) (*model.AuthPayload, error) {
	var user *models.User
	var err error

	switch provider {
	case model.ProviderApple:
		sub, email, verifyErr := auth.VerifyAppleToken(providerToken)
		if verifyErr != nil {
			return nil, fmt.Errorf("apple verification failed: %w", verifyErr)
		}
		user, err = auth.SocialLogin("APPLE", sub, email)

	case model.ProviderGoogle:
		sub, email, verifyErr := auth.VerifyGoogleToken(providerToken)
		if verifyErr != nil {
			return nil, fmt.Errorf("google verification failed: %w", verifyErr)
		}
		user, err = auth.SocialLogin("GOOGLE", sub, email)

	default:
		return nil, ErrInvalidProvider
	}

	if err != nil {
		return nil, fmt.Errorf("social login failed: %w", err)
	}

	return r.Resolver.createAuthSession(user, DeviceMobile)
}

// SendOtp is the resolver for the sendOtp field.
func (r *mutationResolver) SendOtp(ctx context.Context, target string, purpose string) (bool, error) {
	if !IsValidPurpose(purpose) {
		return false, ErrInvalidPurpose
	}

	exceeded, err := otp.CheckRateLimit(target)
	if err != nil {
		return false, fmt.Errorf("rate limit check failed: %w", err)
	}
	if exceeded {
		return false, ErrRateLimitExceeded
	}

	code := otp.Generate()

	if err := otp.SaveOTP(target, code, 5*time.Minute); err != nil {
		return false, fmt.Errorf("failed to save OTP: %w", err)
	}

	if err := otp.IncrementRateLimit(target); err != nil {
		return false, fmt.Errorf("failed to update rate limit: %w", err)
	}

	switch purpose {
	case PurposeCustomerLogin:
		if err := otp.SendEmail(target, code); err != nil {
			return false, fmt.Errorf("failed to send email: %w", err)
		}
	case PurposeCaptainLogin:
		if err := otp.SendSMS(target, code); err != nil {
			return false, fmt.Errorf("failed to send SMS: %w", err)
		}
	}

	return true, nil
}

// VerifyOtp is the resolver for the verifyOtp field.
func (r *mutationResolver) VerifyOtp(ctx context.Context, target string, code string, purpose string) (*model.AuthPayload, error) {
	if !IsValidPurpose(purpose) {
		return nil, ErrInvalidPurpose
	}

	valid, err := otp.VerifyOTP(target, code)
	if err != nil {
		if err == otp.ErrMaxAttemptsReached {
			return nil, ErrMaxAttemptsReached
		}
		return nil, ErrOTPNotFound
	}

	if !valid {
		otp.IncrementFailedAttempts(target)
		return nil, ErrInvalidOTP
	}

	// Delete OTP after verification
	if err := otp.DeleteOTP(target); err != nil {
		fmt.Printf("Warning: failed to delete OTP for %s: %v\n", target, err)
	}

	var user models.User
	role := RoleCustomer

	if purpose == PurposeCaptainLogin {
		role = RoleCaptain
		// Captain login: create or fetch by phone
		if err := db.DB.Where("phone = ?", target).
			FirstOrCreate(&user, models.User{
				Phone:         target,
				Role:          role,
				PhoneVerified: true,
				Status:        "ACTIVE",
			}).
			Omit("email", "provider", "provider_id", "email_verified").
			Error; err != nil {
			return nil, fmt.Errorf("failed to create captain: %w", err)
		}
	} else {
		// Customer login: create or fetch by phone
		if err := db.DB.Where("phone = ?", target).
			FirstOrCreate(&user, models.User{
				Phone:         target,
				Role:          role,
				PhoneVerified: true,
				Status:        "ACTIVE",
			}).
			Omit("email", "provider", "provider_id", "email_verified").
			Error; err != nil {
			return nil, fmt.Errorf("failed to create customer: %w", err)
		}
	}

	return r.Resolver.createAuthSession(&user, DeviceMobile)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refresh string, device model.DeviceType) (*model.AuthPayload, error) {
	deviceStr := string(device)

	if !IsValidDevice(deviceStr) {
		return nil, ErrInvalidDevice
	}

	var session models.RefreshToken
	if err := db.DB.Where("token = ? AND expires_at > ?", refresh, time.Now()).First(&session).Error; err != nil {
		return nil, ErrInvalidRefresh
	}

	var user models.User
	if err := db.DB.First(&user, session.UserID).Error; err != nil {
		return nil, ErrUserNotFound
	}

	tx := db.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	access, newRefresh := jwt.GeneratePair(user.ID, user.Role, deviceStr)

	newSession := &models.RefreshToken{
		UserID:    user.ID,
		Token:     newRefresh,
		Device:    deviceStr,
		ExpiresAt: time.Now().Add(RefreshTokenTTL),
	}

	if err := tx.Create(newSession).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("failed to create session: %w", err)
	}

	if err := tx.Delete(&session).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("failed to rotate token: %w", err)
	}

	if err := tx.Commit().Error; err != nil {
		return nil, fmt.Errorf("transaction failed: %w", err)
	}

	return &model.AuthPayload{
		AccessToken:  access,
		RefreshToken: newRefresh,
		UserID:       int(user.ID),
		Role:         user.Role,
	}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	user, err := middlewares.RequireAuth(ctx)
	if err != nil {
		// Allow logout even without auth
		result := db.DB.Where("token = ?", refreshToken).Delete(&models.RefreshToken{})
		if result.Error != nil {
			return false, fmt.Errorf("logout failed: %w", result.Error)
		}
		return true, nil
	}

	fmt.Printf("User %d is logging out\n", user.UserID)

	result := db.DB.Where("token = ? AND user_id = ?", refreshToken, user.UserID).Delete(&models.RefreshToken{})

	if result.Error != nil {
		return false, fmt.Errorf("logout failed: %w", result.Error)
	}

	if result.RowsAffected == 0 {
		return false, ErrInvalidRefresh
	}

	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (string, error) {
	return "ok", nil
}
