package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
)

// ID is the resolver for the id field.
func (r *chatMessageResolver) ID(ctx context.Context, obj *models.ChatMessage) (int, error) {
	return int(obj.ID), nil
}

// RoomID is the resolver for the roomId field.
func (r *chatMessageResolver) RoomID(ctx context.Context, obj *models.ChatMessage) (int, error) {
	return int(obj.RoomID), nil
}

// SenderID is the resolver for the senderId field.
func (r *chatMessageResolver) SenderID(ctx context.Context, obj *models.ChatMessage) (int, error) {
	return int(obj.SenderID), nil
}

// ReceiverID is the resolver for the receiverId field.
func (r *chatMessageResolver) ReceiverID(ctx context.Context, obj *models.ChatMessage) (int, error) {
	return int(obj.ReceiverID), nil
}

// MessageType is the resolver for the messageType field.
func (r *chatMessageResolver) MessageType(ctx context.Context, obj *models.ChatMessage) (model.MessageType, error) {
	return model.MessageType(obj.MessageType), nil
}

// ID is the resolver for the id field.
func (r *chatRoomResolver) ID(ctx context.Context, obj *models.ChatRoom) (int, error) {
	return int(obj.ID), nil
}

// OrderID is the resolver for the orderId field.
func (r *chatRoomResolver) OrderID(ctx context.Context, obj *models.ChatRoom) (int, error) {
	return int(obj.OrderID), nil
}

// CustomerID is the resolver for the customerId field.
func (r *chatRoomResolver) CustomerID(ctx context.Context, obj *models.ChatRoom) (int, error) {
	return int(obj.CustomerID), nil
}

// CaptainID is the resolver for the captainId field.
func (r *chatRoomResolver) CaptainID(ctx context.Context, obj *models.ChatRoom) (int, error) {
	return int(obj.CaptainID), nil
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*models.ChatMessage, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	msg, err := r.Resolver.ChatService.SendMessage(
		uint(input.RoomID),
		authUser.UserID,
		uint(input.ReceiverID),
		input.Message,
		input.MessageType,
		input.MediaURL,
		input.Latitude,
		input.Longitude,
	)
	if err != nil {
		return nil, err
	}

	// Publish to real-time channel
	r.Resolver.RealtimeService.PublishChatMessage(
		msg.RoomID,
		msg.SenderID,
		msg.ReceiverID,
		msg.Message,
	)

	return msg, nil
}

// MarkMessageAsRead is the resolver for the markMessageAsRead field.
func (r *mutationResolver) MarkMessageAsRead(ctx context.Context, messageID int) (*models.ChatMessage, error) {
	panic(fmt.Errorf("not implemented: MarkMessageAsRead - markMessageAsRead"))
}

// MarkAllMessagesAsRead is the resolver for the markAllMessagesAsRead field.
func (r *mutationResolver) MarkAllMessagesAsRead(ctx context.Context, roomID int) (*model.SuccessResponse, error) {
	panic(fmt.Errorf("not implemented: MarkAllMessagesAsRead - markAllMessagesAsRead"))
}

// ChatRoom is the resolver for the chatRoom field.
func (r *queryResolver) ChatRoom(ctx context.Context, orderID int) (*models.ChatRoom, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	//@@@@@@@@@ changed roomID to orderID @@@@@@@@@@@@@//
	room, err := r.Resolver.ChatService.GetChatRoom(uint(orderID))
	if err != nil {
		return nil, err
	}

	// Check authorization
	if room.CustomerID != authUser.UserID && room.CaptainID != authUser.UserID {
		return nil, errors.New("unauthorized")
	}

	return room, nil
}

// ChatMessages is the resolver for the chatMessages field.
func (r *queryResolver) ChatMessages(ctx context.Context, roomID int, pagination *model.PaginationInput) (*model.ChatMessageConnection, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	messages, total, err := r.Resolver.ChatService.GetMessages(uint(roomID), authUser.UserID, page, pageSize)
	if err != nil {
		return nil, err
	}

	return &model.ChatMessageConnection{
		Edges: messages,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: (int(total) + pageSize - 1) / pageSize,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// UnreadMessageCount is the resolver for the unreadMessageCount field.
func (r *queryResolver) UnreadMessageCount(ctx context.Context) (int, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return 0, err
	}

	count, err := r.Resolver.ChatService.GetUnreadCount(authUser.UserID)
	if err != nil {
		return 0, err
	}

	return int(count), nil
}

// MessageReceived is the resolver for the messageReceived field.
func (r *subscriptionResolver) MessageReceived(ctx context.Context, roomID int) (<-chan *models.ChatMessage, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ch := make(chan *models.ChatMessage)

	go func() {
		defer close(ch)

		channel := fmt.Sprintf("chat:%d", roomID)
		eventCh, _ := r.Resolver.RealtimeService.Subscribe(ctx, channel)

		for event := range eventCh {
			if event.Type == "message.received" {
				payload, ok := event.Payload.(map[string]interface{})
				if !ok {
					continue
				}

				// Create message from payload
				message := &models.ChatMessage{
					RoomID:     uint(roomID),
					SenderID:   uint(payload["sender_id"].(float64)),
					ReceiverID: uint(payload["receiver_id"].(float64)),
					Message:    payload["message"].(string),
				}

				select {
				case ch <- message:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	_ = authUser
	return ch, nil
}

// UserTyping is the resolver for the userTyping field.
func (r *subscriptionResolver) UserTyping(ctx context.Context, roomID int) (<-chan *model.TypingIndicator, error) {
	panic(fmt.Errorf("not implemented: UserTyping - userTyping"))
}

// ChatMessage returns generated.ChatMessageResolver implementation.
func (r *Resolver) ChatMessage() generated.ChatMessageResolver { return &chatMessageResolver{r} }

// ChatRoom returns generated.ChatRoomResolver implementation.
func (r *Resolver) ChatRoom() generated.ChatRoomResolver { return &chatRoomResolver{r} }

type chatMessageResolver struct{ *Resolver }
type chatRoomResolver struct{ *Resolver }
