package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
)

// ID is the resolver for the id field.
func (r *currentLocationResolver) ID(ctx context.Context, obj *models.CurrentLocation) (int, error) {
	return int(obj.ID), nil
}

// UserID is the resolver for the userId field.
func (r *currentLocationResolver) UserID(ctx context.Context, obj *models.CurrentLocation) (int, error) {
	return int(obj.UserID), nil
}

// Source is the resolver for the source field.
func (r *currentLocationResolver) Source(ctx context.Context, obj *models.CurrentLocation) (model.LocationSource, error) {
	return model.LocationSource(obj.Source), nil
}

// ID is the resolver for the id field.
func (r *locationTrackingResolver) ID(ctx context.Context, obj *models.LocationTracking) (int, error) {
	return int(obj.ID), nil
}

// OrderID is the resolver for the orderId field.
func (r *locationTrackingResolver) OrderID(ctx context.Context, obj *models.LocationTracking) (int, error) {
	return int(obj.OrderID), nil
}

// CaptainID is the resolver for the captainId field.
func (r *locationTrackingResolver) CaptainID(ctx context.Context, obj *models.LocationTracking) (int, error) {
	return int(obj.CaptainID), nil
}

// UpdateMyLocation is the resolver for the updateMyLocation field.
func (r *mutationResolver) UpdateMyLocation(ctx context.Context, input model.UpdateLocationInput) (*models.CurrentLocation, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	location, err := r.Resolver.LocationService.UpdateCurrentLocation(
		authUser.UserID,
		input.Latitude,
		input.Longitude,
	)
	if err != nil {
		return nil, err
	}

	return location, nil
}

// TrackOrderLocation is the resolver for the trackOrderLocation field.
func (r *mutationResolver) TrackOrderLocation(ctx context.Context, orderID int, input model.TrackLocationInput) (*models.LocationTracking, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	speed := 0.0
	if input.Speed != nil {
		speed = *input.Speed
	}

	bearing := 0.0
	if input.Bearing != nil {
		bearing = *input.Bearing
	}

	tracking, err := r.Resolver.LocationService.TrackOrderLocation(
		uint(orderID),
		authUser.UserID,
		input.Latitude,
		input.Longitude,
		speed,
		bearing,
	)
	if err != nil {
		return nil, err
	}

	// Publish location update to real-time subscribers
	r.Resolver.RealtimeService.PublishLocationUpdate(
		uint(orderID),
		authUser.UserID,
		input.Latitude,
		input.Longitude,
	)

	return tracking, nil
}

// ToggleLiveTracking is the resolver for the toggleLiveTracking field.
func (r *mutationResolver) ToggleLiveTracking(ctx context.Context, enabled bool) (*models.CurrentLocation, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// TODO: Implement toggle live tracking
	_ = enabled

	location, err := r.Resolver.LocationService.UpdateCurrentLocation(
		authUser.UserID,
		0,
		0,
	)
	if err != nil {
		return nil, err
	}

	return location, nil
}

// MyCurrentLocation is the resolver for the myCurrentLocation field.
func (r *queryResolver) MyCurrentLocation(ctx context.Context) (*models.CurrentLocation, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// TODO: Implement GetCurrentLocation in service
	location, err := r.Resolver.LocationService.UpdateCurrentLocation(
		authUser.UserID,
		0,
		0,
	)
	if err != nil {
		return nil, err
	}

	return location, nil
}

// OrderLocationHistory is the resolver for the orderLocationHistory field.
func (r *queryResolver) OrderLocationHistory(ctx context.Context, orderID int) ([]*models.LocationTracking, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	_ = authUser
	_ = orderID

	// TODO: Implement GetOrderLocationHistory in service
	return []*models.LocationTracking{}, nil
}

// ReverseGeocode is the resolver for the reverseGeocode field.
func (r *queryResolver) ReverseGeocode(ctx context.Context, latitude float64, longitude float64) (*model.GeocodedAddress, error) {
	// TODO: Implement reverse geocoding using Google Maps API or similar
	_ = latitude
	_ = longitude

	// @@@@@@@@@@ changed "" to nil @@@@@@@@@@@@@ //
	return &model.GeocodedAddress{
		FormattedAddress: "Address not available",
		City:             nil,
		State:            nil,
		Country:          nil,
		PostalCode:       nil,
	}, nil
}

// CalculateDistance is the resolver for the calculateDistance field.
func (r *queryResolver) CalculateDistance(ctx context.Context, fromLat float64, fromLng float64, toLat float64, toLng float64) (*model.Distance, error) {
	distanceKm := calculateDistance(fromLat, fromLng, toLat, toLng)
	durationMinutes := int(distanceKm * 2) // Rough estimate: 30 km/h average

	return &model.Distance{
		DistanceKm:      distanceKm,
		DistanceMeters:  distanceKm * 1000,
		DurationMinutes: durationMinutes,
		DurationSeconds: durationMinutes * 60,
	}, nil
}

// TrackOrder is the resolver for the trackOrder field.
func (r *subscriptionResolver) TrackOrder(ctx context.Context, orderID int) (<-chan *models.LocationTracking, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ch := make(chan *models.LocationTracking)

	go func() {
		defer close(ch)

		channel := fmt.Sprintf("order:%d:location", orderID)
		eventCh, _ := r.Resolver.RealtimeService.Subscribe(ctx, channel)

		for event := range eventCh {
			if event.Type == "location.updated" {
				// Parse location data from event payload
				payload, ok := event.Payload.(map[string]interface{})
				if !ok {
					continue
				}

				lat, _ := payload["latitude"].(float64)
				lng, _ := payload["longitude"].(float64)
				captainID, _ := payload["captain_id"].(uint)

				tracking := &models.LocationTracking{
					OrderID:   uint(orderID),
					CaptainID: captainID,
					Latitude:  lat,
					Longitude: lng,
				}

				select {
				case ch <- tracking:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	_ = authUser
	return ch, nil
}

// CurrentLocation returns generated.CurrentLocationResolver implementation.
func (r *Resolver) CurrentLocation() generated.CurrentLocationResolver {
	return &currentLocationResolver{r}
}

// LocationTracking returns generated.LocationTrackingResolver implementation.
func (r *Resolver) LocationTracking() generated.LocationTrackingResolver {
	return &locationTrackingResolver{r}
}

type currentLocationResolver struct{ *Resolver }
type locationTrackingResolver struct{ *Resolver }
