package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"fmt"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
)

// MarkNotificationAsRead is the resolver for the markNotificationAsRead field.
func (r *mutationResolver) MarkNotificationAsRead(ctx context.Context, id int) (*models.Notification, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	notification, err := r.Resolver.NotificationService.MarkAsRead(uint(id), authUser.UserID)
	if err != nil {
		return nil, err
	}

	return notification, nil
}

// MarkAllNotificationsAsRead is the resolver for the markAllNotificationsAsRead field.
func (r *mutationResolver) MarkAllNotificationsAsRead(ctx context.Context) (*model.SuccessResponse, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.Resolver.NotificationService.MarkAllAsRead(authUser.UserID); err != nil {
		return &model.SuccessResponse{
			Success: false,
			Message: stringPtr("Failed to mark notifications as read"),
		}, err
	}

	return &model.SuccessResponse{
		Success: true,
		Message: stringPtr("All notifications marked as read"),
	}, nil
}

// DeleteNotification is the resolver for the deleteNotification field.
func (r *mutationResolver) DeleteNotification(ctx context.Context, id int) (*model.SuccessResponse, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.Resolver.NotificationService.DeleteNotification(uint(id), authUser.UserID); err != nil {
		return &model.SuccessResponse{
			Success: false,
			Message: stringPtr("Failed to delete notification"),
		}, err
	}

	return &model.SuccessResponse{
		Success: true,
		Message: stringPtr("Notification deleted successfully"),
	}, nil
}

// UpdateDeviceToken is the resolver for the updateDeviceToken field.
func (r *mutationResolver) UpdateDeviceToken(ctx context.Context, token string, platform model.DevicePlatform) (*model.SuccessResponse, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.Resolver.NotificationService.UpdateDeviceToken(authUser.UserID, token, string(platform)); err != nil {
		return &model.SuccessResponse{
			Success: false,
			Message: stringPtr("Failed to update device token"),
		}, err
	}

	return &model.SuccessResponse{
		Success: true,
		Message: stringPtr("Device token updated successfully"),
	}, nil
}

// ID is the resolver for the id field.
func (r *notificationResolver) ID(ctx context.Context, obj *models.Notification) (int, error) {
	return int(obj.ID), nil
}

// UserID is the resolver for the userId field.
func (r *notificationResolver) UserID(ctx context.Context, obj *models.Notification) (int, error) {
	return int(obj.UserID), nil
}

// Type is the resolver for the type field.
func (r *notificationResolver) Type(ctx context.Context, obj *models.Notification) (model.NotificationType, error) {
	return model.NotificationType(obj.Type), nil
}

// OrderID is the resolver for the orderId field.
func (r *notificationResolver) OrderID(ctx context.Context, obj *models.Notification) (*int, error) {
	if obj.OrderID == nil {
		return nil, nil
	}
	id := int(*obj.OrderID)
	return &id, nil
}

// TransactionID is the resolver for the transactionId field.
func (r *notificationResolver) TransactionID(ctx context.Context, obj *models.Notification) (*int, error) {
	if obj.TransactionID == nil {
		return nil, nil
	}
	id := int(*obj.TransactionID)
	return &id, nil
}

// Data is the resolver for the data field.
func (r *notificationResolver) Data(ctx context.Context, obj *models.Notification) (map[string]any, error) {
	if obj.Data == "" {
		return make(map[string]any), nil
	}

	var data map[string]any
	if err := json.Unmarshal([]byte(obj.Data), &data); err != nil {
		return make(map[string]any), nil
	}

	return data, nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context, isRead *bool, pagination *model.PaginationInput) (*model.NotificationConnection, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	notifications, total, err := r.Resolver.NotificationService.GetUserNotifications(
		authUser.UserID,
		isRead,
		page,
		pageSize,
	)
	if err != nil {
		return nil, err
	}

	edges := make([]*models.Notification, len(notifications))
	for i, n := range notifications {
		edges[i] = n
	}

	return &model.NotificationConnection{
		Edges: edges,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: int(total)/pageSize + 1,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// UnreadNotificationCount is the resolver for the unreadNotificationCount field.
func (r *queryResolver) UnreadNotificationCount(ctx context.Context) (int, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return 0, err
	}

	count, err := r.Resolver.NotificationService.GetUnreadCount(authUser.UserID)
	if err != nil {
		return 0, err
	}

	return int(count), nil
}

// NotificationReceived is the resolver for the notificationReceived field.
func (r *subscriptionResolver) NotificationReceived(ctx context.Context) (<-chan *models.Notification, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ch := make(chan *models.Notification)

	go func() {
		defer close(ch)

		channel := fmt.Sprintf("user:%d:notifications", authUser.UserID)
		eventCh, _ := r.Resolver.RealtimeService.Subscribe(ctx, channel)

		for event := range eventCh {
			if event.Type == "notification.received" {
				// Parse notification from event payload
				notification, ok := event.Payload.(*models.Notification)
				if !ok {
					continue
				}

				select {
				case ch <- notification:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// Notification returns generated.NotificationResolver implementation.
func (r *Resolver) Notification() generated.NotificationResolver { return &notificationResolver{r} }

type notificationResolver struct{ *Resolver }
