package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"time"
	"turtle/db"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
)

// ID is the resolver for the id field.
func (r *captainEarningsResolver) ID(ctx context.Context, obj *models.CaptainEarnings) (int, error) {
	return int(obj.ID), nil
}

// CaptainID is the resolver for the captainId field.
func (r *captainEarningsResolver) CaptainID(ctx context.Context, obj *models.CaptainEarnings) (int, error) {
	return int(obj.CaptainID), nil
}

// ID is the resolver for the id field.
func (r *couponResolver) ID(ctx context.Context, obj *models.Coupon) (int, error) {
	return int(obj.ID), nil
}

// Type is the resolver for the type field.
func (r *couponResolver) Type(ctx context.Context, obj *models.Coupon) (model.CouponType, error) {
	return model.CouponType(obj.Type), nil
}

// AddMoneyToWallet is the resolver for the addMoneyToWallet field.
func (r *mutationResolver) AddMoneyToWallet(ctx context.Context, amount float64, paymentMethod model.PaymentMethod) (*models.Transaction, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	transaction, err := r.Resolver.PaymentService.AddMoneyToWallet(
		authUser.UserID,
		amount,
		string(paymentMethod),
	)
	if err != nil {
		return nil, err
	}

	return transaction, nil
}

// WithdrawFromWallet is the resolver for the withdrawFromWallet field.
func (r *mutationResolver) WithdrawFromWallet(ctx context.Context, amount float64) (*models.Transaction, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	// Check sufficient balance
	balance, err := r.Resolver.PaymentService.GetWalletBalance(authUser.UserID)
	if err != nil {
		return nil, err
	}

	if balance < amount {
		return nil, errors.New("insufficient balance")
	}

	// TODO: Implement withdrawal logic
	_ = amount

	return nil, errors.New("not yet implemented")
}

// ProcessOrderPayment is the resolver for the processOrderPayment field.
func (r *mutationResolver) ProcessOrderPayment(ctx context.Context, orderID int, paymentMethod model.PaymentMethod) (*models.Transaction, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Get order
	order, err := r.Resolver.OrderService.GetOrderByID(uint(orderID))
	if err != nil {
		return nil, err
	}

	// Verify user owns the order
	if order.CustomerID != authUser.UserID {
		return nil, middlewares.ErrUnauthorized
	}

	// Check if already paid
	if order.PaymentStatus == "PAID" {
		return nil, errors.New("order already paid")
	}

	// Create transaction
	oid := uint(orderID)
	transaction := &models.Transaction{
		UserID:        authUser.UserID,
		OrderID:       &oid,
		TransactionID: generateTransactionID(),
		Type:          "ORDER_PAYMENT",
		Amount:        order.TotalPrice,
		Currency:      "INR",
		PaymentMethod: string(paymentMethod),
		Status:        "SUCCESS",
	}

	// Get current balance
	balance, _ := r.Resolver.PaymentService.GetWalletBalance(authUser.UserID)
	transaction.BalanceBefore = balance

	if paymentMethod == "WALLET" {
		if balance < order.TotalPrice {
			return nil, errors.New("insufficient wallet balance")
		}
		transaction.BalanceAfter = balance - order.TotalPrice
	} else {
		transaction.BalanceAfter = balance
	}

	now := time.Now()
	transaction.ProcessedAt = &now

	if err := db.DB.Create(transaction).Error; err != nil {
		return nil, err
	}

	// Update order payment status
	db.DB.Model(order).Updates(map[string]interface{}{
		"payment_status": "PAID",
		"paid_at":        now,
		"payment_id":     transaction.TransactionID,
	})

	// If wallet payment, deduct from balance
	if paymentMethod == "WALLET" {
		db.DB.Model(&models.User{}).
			Where("id = ?", authUser.UserID).
			Update("wallet_balance", balance-order.TotalPrice)
	}

	return transaction, nil
}

// RequestRefund is the resolver for the requestRefund field.
func (r *mutationResolver) RequestRefund(ctx context.Context, orderID int, reason string) (*models.Transaction, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	order, err := r.Resolver.OrderService.GetOrderByID(uint(orderID))
	if err != nil {
		return nil, err
	}

	if order.CustomerID != authUser.UserID {
		return nil, middlewares.ErrUnauthorized
	}

	if order.Status != "CANCELLED" {
		return nil, errors.New("can only refund cancelled orders")
	}

	if order.PaymentStatus != "PAID" {
		return nil, errors.New("order not paid")
	}

	// Calculate refund amount
	refundAmount := order.CalculateRefundAmount()

	oid := uint(orderID)
	transaction := &models.Transaction{
		UserID:        authUser.UserID,
		OrderID:       &oid,
		TransactionID: generateTransactionID(),
		Type:          "REFUND",
		Amount:        refundAmount,
		Currency:      "INR",
		PaymentMethod: order.PaymentMethod,
		Status:        "SUCCESS",
		Description:   reason,
	}

	balance, _ := r.Resolver.PaymentService.GetWalletBalance(authUser.UserID)
	transaction.BalanceBefore = balance
	transaction.BalanceAfter = balance + refundAmount

	now := time.Now()
	transaction.ProcessedAt = &now

	if err := db.DB.Create(transaction).Error; err != nil {
		return nil, err
	}

	// Update order
	db.DB.Model(order).Updates(map[string]interface{}{
		"payment_status":             "REFUNDED",
		"refunded_at":                now,
		"refund_transaction_id":      transaction.TransactionID,
		"cancellation_refund_amount": refundAmount,
	})

	// Add to wallet
	db.DB.Model(&models.User{}).
		Where("id = ?", authUser.UserID).
		Update("wallet_balance", balance+refundAmount)

	return transaction, nil
}

// CreateCoupon is the resolver for the createCoupon field.
func (r *mutationResolver) CreateCoupon(ctx context.Context, input model.CreateCouponInput) (*models.Coupon, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	coupon := &models.Coupon{
		Code:             input.Code,
		Description:      ptrToString(input.Description),
		Type:             string(input.Type),
		Value:            input.Value,
		MinOrderValue:    ptrToFloat(input.MinOrderValue),
		MaxDiscountValue: ptrToFloat(input.MaxDiscountValue),
		UsageLimit:       ptrToInt(input.UsageLimit),
		PerUserLimit:     ptrToInt(input.PerUserLimit),
		ValidFrom:        input.ValidFrom,
		ValidUntil:       input.ValidUntil,
		IsActive:         true,
		IsPublic:         ptrToBool(input.IsPublic),
		FirstOrderOnly:   ptrToBool(input.FirstOrderOnly),
	}

	if err := db.DB.Create(coupon).Error; err != nil {
		return nil, err
	}

	return coupon, nil
}

// UpdateCoupon is the resolver for the updateCoupon field.
func (r *mutationResolver) UpdateCoupon(ctx context.Context, id int, input model.UpdateCouponInput) (*models.Coupon, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	var coupon models.Coupon
	if err := db.DB.First(&coupon, id).Error; err != nil {
		return nil, err
	}

	updates := make(map[string]interface{})
	if input.Description != nil {
		updates["description"] = *input.Description
	}
	if input.Value != nil {
		updates["value"] = *input.Value
	}
	if input.MinOrderValue != nil {
		updates["min_order_value"] = *input.MinOrderValue
	}
	if input.MaxDiscountValue != nil {
		updates["max_discount_value"] = *input.MaxDiscountValue
	}
	if input.UsageLimit != nil {
		updates["usage_limit"] = *input.UsageLimit
	}
	if input.ValidFrom != nil {
		updates["valid_from"] = *input.ValidFrom
	}
	if input.ValidUntil != nil {
		updates["valid_until"] = *input.ValidUntil
	}

	if len(updates) > 0 {
		if err := db.DB.Model(&coupon).Updates(updates).Error; err != nil {
			return nil, err
		}
	}

	return &coupon, nil
}

// DeactivateCoupon is the resolver for the deactivateCoupon field.
func (r *mutationResolver) DeactivateCoupon(ctx context.Context, id int) (*models.Coupon, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	var coupon models.Coupon
	if err := db.DB.First(&coupon, id).Error; err != nil {
		return nil, err
	}

	if err := db.DB.Model(&coupon).Update("is_active", false).Error; err != nil {
		return nil, err
	}

	return &coupon, nil
}

// MyWallet is the resolver for the myWallet field.
func (r *queryResolver) MyWallet(ctx context.Context) (*model.Wallet, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	balance, err := r.Resolver.PaymentService.GetWalletBalance(authUser.UserID)
	if err != nil {
		return nil, err
	}

	return &model.Wallet{
		Balance:  balance,
		Currency: "INR",
	}, nil
}

// MyTransactions is the resolver for the myTransactions field.
func (r *queryResolver) MyTransactions(ctx context.Context, typeArg *model.TransactionType, pagination *model.PaginationInput) (*model.TransactionConnection, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	var transactions []*models.Transaction
	var total int64

	query := db.DB.Model(&models.Transaction{}).Where("user_id = ?", authUser.UserID)

	if typeArg != nil {
		query = query.Where("type = ?", string(*typeArg))
	}

	query.Count(&total)

	offset := (page - 1) * pageSize
	if err := query.Order("created_at DESC").Offset(offset).Limit(pageSize).Find(&transactions).Error; err != nil {
		return nil, err
	}

	return &model.TransactionConnection{
		Edges: transactions,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: int(total)/pageSize + 1,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id int) (*models.Transaction, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var transaction models.Transaction
	if err := db.DB.Where("id = ? AND user_id = ?", id, authUser.UserID).First(&transaction).Error; err != nil {
		return nil, err
	}

	return &transaction, nil
}

// AvailableCoupons is the resolver for the availableCoupons field.
func (r *queryResolver) AvailableCoupons(ctx context.Context) ([]*models.Coupon, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var coupons []*models.Coupon
	now := time.Now()

	if err := db.DB.Where("is_active = true AND is_public = true AND valid_from <= ? AND valid_until >= ?", now, now).
		Find(&coupons).Error; err != nil {
		return nil, err
	}

	_ = authUser
	return coupons, nil
}

// ValidateCoupon is the resolver for the validateCoupon field.
func (r *queryResolver) ValidateCoupon(ctx context.Context, code string, orderValue float64) (*model.CouponValidation, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	valid, message, discount := r.Resolver.PricingService.ValidateCoupon(code, orderValue, authUser.UserID)

	return &model.CouponValidation{
		IsValid:        valid,
		Message:        stringPtr(message),
		DiscountAmount: floatPtr(discount),
	}, nil
}

// MyCaptainEarnings is the resolver for the myCaptainEarnings field.
func (r *queryResolver) MyCaptainEarnings(ctx context.Context, startDate time.Time, endDate time.Time) (*model.EarningsSummary, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	var earnings []models.CaptainEarnings
	if err := db.DB.Where("captain_id = ? AND date >= ? AND date <= ?", authUser.UserID, startDate, endDate).
		Find(&earnings).Error; err != nil {
		return nil, err
	}

	// Aggregate totals
	summary := &model.EarningsSummary{
		TotalEarnings:   0,
		NetEarnings:     0,
		TipsReceived:    0,
		BonusEarnings:   0,
		TotalOrders:     0,
		CompletedOrders: 0,
		TotalDistance:   0,
	}

	for _, e := range earnings {
		summary.TotalEarnings += e.TotalEarnings
		summary.NetEarnings += e.NetEarnings
		summary.TipsReceived += e.TipsReceived
		summary.BonusEarnings += e.BonusEarnings
		summary.TotalOrders += e.TotalOrders
		summary.CompletedOrders += e.CompletedOrders
		summary.TotalDistance += e.TotalDistance
	}

	return summary, nil
}

// CaptainEarningsByDate is the resolver for the captainEarningsByDate field.
func (r *queryResolver) CaptainEarningsByDate(ctx context.Context, date time.Time) (*models.CaptainEarnings, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	var earnings models.CaptainEarnings
	if err := db.DB.Where("captain_id = ? AND date = ?", authUser.UserID, date.Format("2006-01-02")).
		First(&earnings).Error; err != nil {
		return nil, err
	}

	return &earnings, nil
}

// ID is the resolver for the id field.
func (r *transactionResolver) ID(ctx context.Context, obj *models.Transaction) (int, error) {
	return int(obj.ID), nil
}

// UserID is the resolver for the userId field.
func (r *transactionResolver) UserID(ctx context.Context, obj *models.Transaction) (int, error) {
	return int(obj.UserID), nil
}

// OrderID is the resolver for the orderId field.
func (r *transactionResolver) OrderID(ctx context.Context, obj *models.Transaction) (*int, error) {
	if obj.OrderID == nil {
		return nil, nil
	}
	id := int(*obj.OrderID)
	return &id, nil
}

// Type is the resolver for the type field.
func (r *transactionResolver) Type(ctx context.Context, obj *models.Transaction) (model.TransactionType, error) {
	return model.TransactionType(obj.Type), nil
}

// PaymentMethod is the resolver for the paymentMethod field.
func (r *transactionResolver) PaymentMethod(ctx context.Context, obj *models.Transaction) (*model.PaymentMethod, error) {
	if obj.PaymentMethod == "" {
		return nil, nil
	}
	pm := model.PaymentMethod(obj.PaymentMethod)
	return &pm, nil
}

// Status is the resolver for the status field.
func (r *transactionResolver) Status(ctx context.Context, obj *models.Transaction) (model.TransactionStatus, error) {
	return model.TransactionStatus(obj.Status), nil
}

// CaptainEarnings returns generated.CaptainEarningsResolver implementation.
func (r *Resolver) CaptainEarnings() generated.CaptainEarningsResolver {
	return &captainEarningsResolver{r}
}

// Coupon returns generated.CouponResolver implementation.
func (r *Resolver) Coupon() generated.CouponResolver { return &couponResolver{r} }

// Transaction returns generated.TransactionResolver implementation.
func (r *Resolver) Transaction() generated.TransactionResolver { return &transactionResolver{r} }

type captainEarningsResolver struct{ *Resolver }
type couponResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
