package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"errors"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
)

// RateUser creates a rating
func (r *mutationResolver) RateUser(ctx context.Context, input model.RateUserInput) (*models.Rating, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	rating, err := r.Resolver.RatingService.CreateRating(
		uint(input.OrderID),
		authUser.UserID,
		uint(input.RatedUserID),
		input.Rating,
		ptrToString(input.Comment),
	)
	if err != nil {
		return nil, err
	}

	return rating, nil
}

// UpdateRating updates an existing rating
func (r *mutationResolver) UpdateRating(ctx context.Context, ratingID int, input model.UpdateRatingInput) (*models.Rating, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// TODO: Implement update rating in service
	_ = authUser
	_ = input

	return nil, errors.New("not yet implemented")
}

// FlagRating flags a rating as inappropriate
func (r *mutationResolver) FlagRating(ctx context.Context, ratingID int, reason string) (*models.Rating, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	_ = authUser
	_ = reason

	return nil, errors.New("not yet implemented")
}

// UnflagRating removes flag from a rating
func (r *mutationResolver) UnflagRating(ctx context.Context, ratingID int) (*models.Rating, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	return nil, errors.New("not yet implemented")
}

// UserRatings retrieves ratings for a user
func (r *queryResolver) UserRatings(ctx context.Context, userID int, pagination *model.PaginationInput) (*model.RatingConnection, error) {
	page, pageSize := getPaginationParams(pagination)

	// TODO: Implement GetUserRatings in rating service
	_ = userID

	return &model.RatingConnection{
		Edges: []*models.Rating{},
		PageInfo: &model.PaginationInfo{
			Total:      0,
			Page:       page,
			PageSize:   pageSize,
			TotalPages: 0,
			HasNext:    false,
			HasPrev:    false,
		},
	}, nil
}

// OrderRating retrieves rating for an order
func (r *queryResolver) OrderRating(ctx context.Context, orderID int) (*models.Rating, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	_ = authUser

	return nil, errors.New("not yet implemented")
}

// MyReceivedRatings retrieves ratings received by user
func (r *queryResolver) MyReceivedRatings(ctx context.Context, pagination *model.PaginationInput) (*model.RatingConnection, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	_ = authUser

	return &model.RatingConnection{
		Edges: []*models.Rating{},
		PageInfo: &model.PaginationInfo{
			Total:      0,
			Page:       page,
			PageSize:   pageSize,
			TotalPages: 0,
			HasNext:    false,
			HasPrev:    false,
		},
	}, nil
}

// MyGivenRatings retrieves ratings given by user
func (r *queryResolver) MyGivenRatings(ctx context.Context, pagination *model.PaginationInput) (*model.RatingConnection, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	_ = authUser

	return &model.RatingConnection{
		Edges: []*models.Rating{},
		PageInfo: &model.PaginationInfo{
			Total:      0,
			Page:       page,
			PageSize:   pageSize,
			TotalPages: 0,
			HasNext:    false,
			HasPrev:    false,
		},
	}, nil
}

// ID is the resolver for the id field.
func (r *ratingResolver) ID(ctx context.Context, obj *models.Rating) (int, error) {
	return int(obj.ID), nil
}

// OrderID is the resolver for the orderId field.
func (r *ratingResolver) OrderID(ctx context.Context, obj *models.Rating) (int, error) {
	return int(obj.OrderID), nil
}

// UserID is the resolver for the userId field.
func (r *ratingResolver) UserID(ctx context.Context, obj *models.Rating) (int, error) {
	return int(obj.UserID), nil
}

// RatedUserID is the resolver for the ratedUserId field.
func (r *ratingResolver) RatedUserID(ctx context.Context, obj *models.Rating) (int, error) {
	return int(obj.RatedUserID), nil
}

// Tags is the resolver for the tags field.
func (r *ratingResolver) Tags(ctx context.Context, obj *models.Rating) ([]string, error) {
	if obj.Tags == "" {
		return []string{}, nil
	}

	var tags []string
	if err := json.Unmarshal([]byte(obj.Tags), &tags); err != nil {
		return []string{}, nil
	}

	return tags, nil
}

// Rating returns generated.RatingResolver implementation.
func (r *Resolver) Rating() generated.RatingResolver { return &ratingResolver{r} }

type ratingResolver struct{ *Resolver }
