package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"time"
	"turtle/graph/generated"
	"turtle/graph/model"
)

// Placeholder is the resolver for the _placeholder field.
// This is a no-op mutation used to satisfy GraphQL schema requirements
func (r *mutationResolver) Placeholder(ctx context.Context) (*bool, error) {
	result := true
	return &result, nil
}

// Health is the resolver for the health field.
// Returns true if the API is healthy and all dependencies are available
func (r *queryResolver) Health(ctx context.Context) (bool, error) {
	// Check database connection
	if err := r.Resolver.userRepo.HealthCheck(ctx); err != nil {
		return false, nil
	}

	// Check cache connection
	if _, err := r.Resolver.cache.Get(ctx, "health_check"); err != nil {
		// Cache error is not critical, just log it
		fmt.Printf("Cache health check warning: %v\n", err)
	}

	return true, nil
}

// Version is the resolver for the version field.
// Returns the current API version
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	return APIVersion, nil
}

// UserUpdated is the resolver for the userUpdated subscription field.
// Subscribes to user profile updates
func (r *subscriptionResolver) UserUpdated(ctx context.Context, userID string) (<-chan *model.User, error) {
	// Create a channel for user updates
	updates := make(chan *model.User, 1)

	// Start a goroutine to handle subscription
	go func() {
		defer close(updates)

		// Create a ticker to periodically check for updates
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		// Track last known version
		var lastVersion int64

		for {
			select {
			case <-ctx.Done():
				// Client disconnected
				return
			case <-ticker.C:
				// Fetch user and check if updated
				user, err := r.Resolver.userRepo.FindByID(ctx, userID)
				if err != nil {
					// Log error but don't close channel
					fmt.Printf("Error fetching user in subscription: %v\n", err)
					continue
				}

				// Check if user was updated (using UpdatedAt as version)
				currentVersion := user.UpdatedAt().Unix()
				if lastVersion == 0 {
					lastVersion = currentVersion
					continue
				}

				if currentVersion > lastVersion {
					lastVersion = currentVersion
					// Send update to client
					select {
					case updates <- userToGraphQL(user):
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return updates, nil
}

// CaptainLocationUpdated is the resolver for the captainLocationUpdated subscription field.
// Subscribes to captain location updates
func (r *subscriptionResolver) CaptainLocationUpdated(ctx context.Context, captainID string) (<-chan *model.Location, error) {
	// Create a channel for location updates
	updates := make(chan *model.Location, 1)

	// Start a goroutine to handle subscription
	go func() {
		defer close(updates)

		// Create a ticker to periodically check for location updates
		ticker := time.NewTicker(3 * time.Second)
		defer ticker.Stop()

		// Track last known location
		var lastLat, lastLng float64

		for {
			select {
			case <-ctx.Done():
				// Client disconnected
				return
			case <-ticker.C:
				// Fetch captain and check location
				captain, err := r.Resolver.userRepo.FindByID(ctx, captainID)
				if err != nil {
					fmt.Printf("Error fetching captain in subscription: %v\n", err)
					continue
				}

				// Check if captain has a profile and location
				if !captain.IsCaptain() || captain.CaptainProfile() == nil {
					continue
				}

				profile := captain.CaptainProfile()
				if profile.CurrentLocation() == nil {
					continue
				}

				currentLoc := profile.CurrentLocation()
				currentLat := currentLoc.Latitude()
				currentLng := currentLoc.Longitude()

				// Check if location changed
				if lastLat == 0 && lastLng == 0 {
					lastLat = currentLat
					lastLng = currentLng
					continue
				}

				// Send update if location changed (more than 10 meters)
				if distance(lastLat, lastLng, currentLat, currentLng) > 0.01 { // ~10 meters
					lastLat = currentLat
					lastLng = currentLng

					location := &model.Location{
						Latitude:  currentLat,
						Longitude: currentLng,
					}

					select {
					case updates <- location:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return updates, nil
}

// CaptainAvailabilityChanged is the resolver for the captainAvailabilityChanged subscription field.
// Subscribes to captain availability changes (online/offline)
func (r *subscriptionResolver) CaptainAvailabilityChanged(ctx context.Context, captainID string) (<-chan *model.CaptainAvailability, error) {
	// Create a channel for availability updates
	updates := make(chan *model.CaptainAvailability, 1)

	// Start a goroutine to handle subscription
	go func() {
		defer close(updates)

		// Create a ticker to periodically check for availability changes
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		// Track last known availability
		var lastAvailability *bool

		for {
			select {
			case <-ctx.Done():
				// Client disconnected
				return
			case <-ticker.C:
				// Fetch captain and check availability
				captain, err := r.Resolver.userRepo.FindByID(ctx, captainID)
				if err != nil {
					fmt.Printf("Error fetching captain in subscription: %v\n", err)
					continue
				}

				// Check if captain has a profile
				if !captain.IsCaptain() || captain.CaptainProfile() == nil {
					continue
				}

				profile := captain.CaptainProfile()
				currentAvailability := profile.IsAvailable()

				// Initialize on first check
				if lastAvailability == nil {
					lastAvailability = &currentAvailability
					continue
				}

				// Check if availability changed
				if *lastAvailability != currentAvailability {
					*lastAvailability = currentAvailability

					availability := &model.CaptainAvailability{
						CaptainID:   captainID,
						IsAvailable: currentAvailability,
						Timestamp:   time.Now(),
					}

					// Include location if available
					if profile.CurrentLocation() != nil {
						availability.Location = &model.Location{
							Latitude:  profile.CurrentLocation().Latitude(),
							Longitude: profile.CurrentLocation().Longitude(),
						}
					}

					select {
					case updates <- availability:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return updates, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
