package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
	"turtle/services/support"
)

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input model.CreateTicketInput) (*models.SupportTicket, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var orderID *uint
	if input.OrderID != nil {
		oid := uint(*input.OrderID)
		orderID = &oid
	}

	priority := "MEDIUM"
	if input.Priority != nil {
		priority = string(*input.Priority)
	}

	ticketInput := support.CreateTicketInput{
		UserID:      authUser.UserID,
		OrderID:     orderID,
		Subject:     input.Subject,
		Description: input.Description,
		Category:    string(input.Category),
		Priority:    priority,
		Attachments: input.Attachments,
	}

	ticket, err := r.Resolver.SupportService.CreateTicket(ticketInput)
	if err != nil {
		return nil, err
	}

	return ticket, nil
}

// AddTicketMessage is the resolver for the addTicketMessage field.
func (r *mutationResolver) AddTicketMessage(ctx context.Context, ticketID int, message string, attachments []string) (*models.SupportTicket, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ticket, err := r.Resolver.SupportService.AddTicketMessage(
		uint(ticketID),
		message,
		attachments,
	)
	if err != nil {
		return nil, err
	}

	_ = authUser
	return ticket, nil
}

// CloseTicket is the resolver for the closeTicket field.
func (r *mutationResolver) CloseTicket(ctx context.Context, ticketID int) (*models.SupportTicket, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ticket, err := r.Resolver.SupportService.CloseTicket(uint(ticketID), authUser.UserID)
	if err != nil {
		return nil, err
	}

	return ticket, nil
}

// AssignTicket is the resolver for the assignTicket field.
func (r *mutationResolver) AssignTicket(ctx context.Context, ticketID int, adminID int) (*models.SupportTicket, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	ticket, err := r.Resolver.SupportService.AssignTicket(uint(ticketID), uint(adminID))
	if err != nil {
		return nil, err
	}

	return ticket, nil
}

// UpdateTicketStatus is the resolver for the updateTicketStatus field.
func (r *mutationResolver) UpdateTicketStatus(ctx context.Context, ticketID int, status model.TicketStatus, message *string) (*models.SupportTicket, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	statusStr := string(status)
	ticket, err := r.Resolver.SupportService.UpdateTicketStatus(uint(ticketID), &statusStr, message)
	if err != nil {
		return nil, err
	}

	return ticket, nil
}

// UpdateTicketPriority is the resolver for the updateTicketPriority field.
func (r *mutationResolver) UpdateTicketPriority(ctx context.Context, ticketID int, priority model.TicketPriority) (*models.SupportTicket, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	ticket, err := r.Resolver.SupportService.UpdateTicketPriority(uint(ticketID), string(priority))
	if err != nil {
		return nil, err
	}

	return ticket, nil
}

// MyTickets is the resolver for the myTickets field.
func (r *queryResolver) MyTickets(ctx context.Context, status *model.TicketStatus, pagination *model.PaginationInput) (*model.TicketConnection, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	var statusStr *string
	if status != nil {
		s := string(*status)
		statusStr = &s
	}

	tickets, total, err := r.Resolver.SupportService.GetUserTickets(authUser.UserID, statusStr, page, pageSize)
	if err != nil {
		return nil, err
	}

	edges := make([]*models.SupportTicket, len(tickets))
	for i, t := range tickets {
		edges[i] = t
	}

	return &model.TicketConnection{
		Edges: edges,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: int(total)/pageSize + 1,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id int) (*models.SupportTicket, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ticket, err := r.Resolver.SupportService.GetTicketByID(uint(id))
	if err != nil {
		return nil, err
	}

	// Check authorization
	if ticket.UserID != authUser.UserID && authUser.Role != RoleAdmin {
		return nil, middlewares.ErrUnauthorized
	}

	return ticket, nil
}

// TicketByNumber is the resolver for the ticketByNumber field.
func (r *queryResolver) TicketByNumber(ctx context.Context, ticketNumber string) (*models.SupportTicket, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	ticket, err := r.Resolver.SupportService.GetTicketByNumber(ticketNumber)
	if err != nil {
		return nil, err
	}

	// Check authorization
	if ticket.UserID != authUser.UserID && authUser.Role != RoleAdmin {
		return nil, middlewares.ErrUnauthorized
	}

	return ticket, nil
}

// AllTickets is the resolver for the allTickets field.
func (r *queryResolver) AllTickets(ctx context.Context, status *model.TicketStatus, priority *model.TicketPriority, pagination *model.PaginationInput) (*model.TicketConnection, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	var statusStr *string
	if status != nil {
		s := string(*status)
		statusStr = &s
	}

	var priorityStr *string
	if priority != nil {
		p := string(*priority)
		priorityStr = &p
	}

	tickets, total, err := r.Resolver.SupportService.GetAllTickets(statusStr, priorityStr, page, pageSize)
	if err != nil {
		return nil, err
	}

	edges := make([]*models.SupportTicket, len(tickets))
	for i, t := range tickets {
		edges[i] = t
	}

	return &model.TicketConnection{
		Edges: edges,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: int(total)/pageSize + 1,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// ID is the resolver for the id field.
func (r *supportTicketResolver) ID(ctx context.Context, obj *models.SupportTicket) (int, error) {
	return int(obj.ID), nil
}

// UserID is the resolver for the userId field.
func (r *supportTicketResolver) UserID(ctx context.Context, obj *models.SupportTicket) (int, error) {
	return int(obj.UserID), nil
}

// OrderID is the resolver for the orderId field.
func (r *supportTicketResolver) OrderID(ctx context.Context, obj *models.SupportTicket) (*int, error) {
	if obj.OrderID == nil {
		return nil, nil
	}
	id := int(*obj.OrderID)
	return &id, nil
}

// Category is the resolver for the category field.
func (r *supportTicketResolver) Category(ctx context.Context, obj *models.SupportTicket) (model.TicketCategory, error) {
	return model.TicketCategory(obj.Category), nil
}

// Status is the resolver for the status field.
func (r *supportTicketResolver) Status(ctx context.Context, obj *models.SupportTicket) (model.TicketStatus, error) {
	return model.TicketStatus(obj.Status), nil
}

// Priority is the resolver for the priority field.
func (r *supportTicketResolver) Priority(ctx context.Context, obj *models.SupportTicket) (model.TicketPriority, error) {
	return model.TicketPriority(obj.Priority), nil
}

// AssignedToAdminID is the resolver for the assignedToAdminId field.
func (r *supportTicketResolver) AssignedToAdminID(ctx context.Context, obj *models.SupportTicket) (*int, error) {
	if obj.AssignedToAdminID == nil {
		return nil, nil
	}
	id := int(*obj.AssignedToAdminID)
	return &id, nil
}

// AssignedToAdmin is the resolver for the assignedToAdmin field.
func (r *supportTicketResolver) AssignedToAdmin(ctx context.Context, obj *models.SupportTicket) (*models.User, error) {
	if obj.AssignedToAdminID == nil {
		return nil, nil
	}
	return obj.Admin, nil
}

// Attachments is the resolver for the attachments field.
func (r *supportTicketResolver) Attachments(ctx context.Context, obj *models.SupportTicket) ([]string, error) {
	if obj.Attachments == "" {
		return []string{}, nil
	}

	var attachments []string
	if err := json.Unmarshal([]byte(obj.Attachments), &attachments); err != nil {
		return []string{}, nil
	}

	return attachments, nil
}

// Messages is the resolver for the messages field.
func (r *supportTicketResolver) Messages(ctx context.Context, obj *models.SupportTicket) ([]*model.TicketMessage, error) {
	// TODO: Implement ticket messages from separate table
	// For now return empty array
	return []*model.TicketMessage{}, nil
}

// SupportTicket returns generated.SupportTicketResolver implementation.
func (r *Resolver) SupportTicket() generated.SupportTicketResolver { return &supportTicketResolver{r} }

type supportTicketResolver struct{ *Resolver }
