package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
	"turtle/db"
	"turtle/graph/generated"
	"turtle/graph/model"
	"turtle/middlewares"
	"turtle/models"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*models.User, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.UpdateProfile(
		authUser.UserID,
		input.FirstName,
		input.LastName,
		input.Email,
		input.Phone,
	)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// UpdateProfilePicture is the resolver for the updateProfilePicture field.
func (r *mutationResolver) UpdateProfilePicture(ctx context.Context, imageURL string) (*models.User, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.UpdateProfilePicture(authUser.UserID, imageURL)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// UpdateCaptainProfile is the resolver for the updateCaptainProfile field.
func (r *mutationResolver) UpdateCaptainProfile(ctx context.Context, input model.UpdateCaptainProfileInput) (*models.User, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	var licenseExpiry *time.Time
	if input.LicenseExpiry != nil {
		licenseExpiry = input.LicenseExpiry
	}

	user, err := r.Resolver.UserService.UpdateCaptainProfile(
		authUser.UserID,
		input.VehicleType,
		input.VehicleNumber,
		input.VehicleModel,
		input.LicenseNumber,
		licenseExpiry,
	)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// ToggleAvailability is the resolver for the toggleAvailability field.
func (r *mutationResolver) ToggleAvailability(ctx context.Context, isAvailable bool) (*models.User, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.ToggleAvailability(authUser.UserID, isAvailable)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// UpdateCurrentLocation is the resolver for the updateCurrentLocation field.
func (r *mutationResolver) UpdateCurrentLocation(ctx context.Context, latitude float64, longitude float64) (*models.User, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.UpdateCurrentLocation(authUser.UserID, latitude, longitude)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// SubmitKYCDocuments is the resolver for the submitKYCDocuments field.
func (r *mutationResolver) SubmitKYCDocuments(ctx context.Context, input model.KYCDocumentsInput) (*models.User, error) {
	authUser, err := middlewares.RequireRole(ctx, RoleCaptain)
	if err != nil {
		return nil, err
	}

	// Convert documents to JSON
	documentsJSON, err := json.Marshal(input.AadhaarURL)
	if err != nil {
		return nil, fmt.Errorf("failed to process documents: %w", err)
	}

	updates := map[string]interface{}{
		"kyc_documents": string(documentsJSON),
		"kyc_status":    "PENDING",
	}

	if err := db.DB.Model(&models.User{}).Where("id = ?", authUser.UserID).
		Updates(updates).Error; err != nil {
		return nil, err
	}

	return r.Resolver.UserService.GetUserByID(authUser.UserID)
}

// UpdateUserStatus is the resolver for the updateUserStatus field.
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, userID int, status model.UserStatus) (*models.User, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.UpdateUserStatus(uint(userID), string(status))
	if err != nil {
		return nil, err
	}

	return user, nil
}

// ApproveKyc is the resolver for the approveKYC field.
func (r *mutationResolver) ApproveKyc(ctx context.Context, userID int, approved bool, reason *string) (*models.User, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.ApproveKYC(uint(userID), approved, reason)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// BlockUser is the resolver for the blockUser field.
func (r *mutationResolver) BlockUser(ctx context.Context, userID int, reason string) (*models.User, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.UpdateUserStatus(uint(userID), "BLOCKED")
	if err != nil {
		return nil, err
	}

	// TODO: Log the block reason
	_ = reason

	return user, nil
}

// UnblockUser is the resolver for the unblockUser field.
func (r *mutationResolver) UnblockUser(ctx context.Context, userID int) (*models.User, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.UpdateUserStatus(uint(userID), "ACTIVE")
	if err != nil {
		return nil, err
	}

	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	user, err := r.Resolver.UserService.GetUserByID(authUser.UserID)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id int) (*models.User, error) {
	user, err := r.Resolver.UserService.GetUserByID(uint(id))
	if err != nil {
		return nil, err
	}

	return user, nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, role *model.UserRole, pagination *model.PaginationInput) (*model.UserConnection, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	roleStr := ""
	if role != nil {
		roleStr = string(*role)
	}

	users, total, err := r.Resolver.UserService.SearchUsers(query, roleStr, page, pageSize)
	if err != nil {
		return nil, err
	}

	return &model.UserConnection{
		Edges: users,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: (int(total) + pageSize - 1) / pageSize,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// GetCaptains is the resolver for the getCaptains field.
func (r *queryResolver) GetCaptains(ctx context.Context, status *model.CaptainStatus, isAvailable *bool, pagination *model.PaginationInput) (*model.UserConnection, error) {
	_, err := middlewares.RequireRole(ctx, RoleAdmin)
	if err != nil {
		return nil, err
	}

	page, pageSize := getPaginationParams(pagination)

	var captains []*models.User
	var total int64

	query := db.DB.Model(&models.User{}).Where("role = ?", "CAPTAIN")

	if status != nil {
		query = query.Where("kyc_status = ?", string(*status))
	}

	if isAvailable != nil {
		query = query.Where("is_available = ?", *isAvailable)
	}

	query.Count(&total)

	offset := (page - 1) * pageSize
	if err := query.Order("created_at DESC").
		Offset(offset).Limit(pageSize).
		Find(&captains).Error; err != nil {
		return nil, err
	}

	return &model.UserConnection{
		Edges: captains,
		PageInfo: &model.PaginationInfo{
			Total:      int(total),
			Page:       page,
			PageSize:   pageSize,
			TotalPages: (int(total) + pageSize - 1) / pageSize,
			HasNext:    page*pageSize < int(total),
			HasPrev:    page > 1,
		},
	}, nil
}

// GetNearbyCaptains is the resolver for the getNearbyCaptains field.
func (r *queryResolver) GetNearbyCaptains(ctx context.Context, latitude float64, longitude float64, radiusKm float64) ([]*models.User, error) {
	authUser, err := middlewares.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	captains, err := r.Resolver.UserService.GetNearbyCaptains(latitude, longitude, radiusKm)
	if err != nil {
		return nil, err
	}

	_ = authUser
	return captains, nil
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *models.User) (int, error) {
	return int(obj.ID), nil
}

// FullName is the resolver for the fullName field.
func (r *userResolver) FullName(ctx context.Context, obj *models.User) (*string, error) {
	return stringPtr(obj.GetFullName()), nil
}

// Role is the resolver for the role field.
func (r *userResolver) Role(ctx context.Context, obj *models.User) (model.UserRole, error) {
	return model.UserRole(obj.Role), nil
}

// Status is the resolver for the status field.
func (r *userResolver) Status(ctx context.Context, obj *models.User) (model.UserStatus, error) {
	return model.UserStatus(obj.Status), nil
}

// VehicleType is the resolver for the vehicleType field.
func (r *userResolver) VehicleType(ctx context.Context, obj *models.User) (*model.VehicleType, error) {
	if !obj.IsCaptain() || ptrToString(obj.VehicleType) == "" {
		return nil, nil
	}
	// vType := model.VehicleType(obj.VehicleType)
	vType := model.VehicleTypeBike
	return &vType, nil
}

// CurrentLocation is the resolver for the currentLocation field.
func (r *userResolver) CurrentLocation(ctx context.Context, obj *models.User) (*model.Location, error) {
	if obj.CurrentLat == 0 && obj.CurrentLng == 0 {
		return nil, nil
	}

	return &model.Location{
		Latitude:  obj.CurrentLat,
		Longitude: obj.CurrentLng,
	}, nil
}

// KycStatus is the resolver for the kycStatus field.
func (r *userResolver) KycStatus(ctx context.Context, obj *models.User) (*model.CaptainStatus, error) {
	if !obj.IsCaptain() {
		return nil, nil
	}
	status := model.CaptainStatus(obj.KycStatus)
	return &status, nil
}

// KycDocuments is the resolver for the kycDocuments field.
func (r *userResolver) KycDocuments(ctx context.Context, obj *models.User) ([]string, error) {
	return  nil, nil
	// if !obj.IsCaptain() || obj.KycDocuments == "" {
	// 	return []string{}, nil
	// }

	// var documents []string
	// if err := json.Unmarshal([]byte(obj.KycDocuments), &documents); err != nil {
	// 	return []string{}, nil
	// }

	// return documents, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
