package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"turtle/graph/model"
	"turtle/internal/domain"
	"turtle/internal/domain/aggregates"
	"turtle/internal/domain/valueobjects"
	pkgErrors "turtle/pkg/errors"
)

// UpdateProfile updates user profile
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Fetch user
	user, err := r.Resolver.userService.GetUser(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Handle profile picture upload if provided
	profilePic := user.ProfilePic()
	if input.ProfilePic != nil {
		// TODO: Upload file and get URL
		// uploadedURL, err := uploadFile(ctx, input.ProfilePic)
		// profilePic = uploadedURL
	}

	// Update profile
	firstName := stringValue(input.FirstName)
	if firstName == "" {
		firstName = user.FirstName()
	}

	lastName := stringValue(input.LastName)
	if lastName == "" {
		lastName = user.LastName()
	}

	// Save changes
	user, err = r.Resolver.userService.UpdateProfile(ctx, userID, firstName, lastName, profilePic)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(user), nil
}

// UpdateVehicle updates captain's vehicle information
func (r *mutationResolver) UpdateVehicle(ctx context.Context, input model.UpdateVehicleInput) (*model.CaptainProfile, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	user, err := r.Resolver.userService.UpdateVehicle(
		ctx,
		userID,
		aggregates.VehicleType(input.VehicleType),
		input.VehicleNumber,
		input.VehicleModel,
	)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return captainProfileToGraphQL(user.CaptainProfile()), nil
}

// SubmitKyc submits KYC documents
func (r *mutationResolver) SubmitKyc(ctx context.Context, input model.SubmitKYCInput) (*model.CaptainProfile, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return nil, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	documents := map[string]string{
		"LICENSE":       "url_to_license",
		"VEHICLE_RC":    "url_to_rc",
		"PROFILE_PHOTO": "url_to_photo",
	}
	user, err := r.Resolver.userService.SubmitKYC(ctx, userID, documents)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return captainProfileToGraphQL(user.CaptainProfile()), nil
}

// GoOnline sets captain as available
func (r *mutationResolver) GoOnline(ctx context.Context, input model.GoOnlineInput) (bool, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return false, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Fetch user
	_, err := r.Resolver.userService.GetUser(ctx, userID)
	if err != nil {
		return false, handleError(ctx, err)
	}

	// Create location
	location, err := valueobjects.NewLocation(input.Location.Latitude, input.Location.Longitude)
	if err != nil {
		return false, handleError(ctx, err)
	}

	// Save changes
	err = r.Resolver.userService.GoOnline(ctx, userID, location)
	if err != nil {
		return false, handleError(ctx, err)
	}

	return true, nil
}

// GoOffline sets captain as unavailable
func (r *mutationResolver) GoOffline(ctx context.Context) (bool, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return false, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Fetch user
	_, err := r.Resolver.userService.GetUser(ctx, userID)
	if err != nil {
		return false, handleError(ctx, err)
	}

	// Go offline
	err = r.Resolver.userService.GoOffline(ctx, userID)
	if err != nil {
		return false, handleError(ctx, err)
	}

	return true, nil
}

// UpdateLocation updates captain's current location
func (r *mutationResolver) UpdateLocation(ctx context.Context, input model.UpdateLocationInput) (bool, error) {
	userID, idErr := getUserIDFromContext(ctx)
	if idErr != nil {
		return false, pkgErrors.ErrUnauthorized("Not authenticated")
	}

	// Create location
	location, err := valueobjects.NewLocation(input.Location.Latitude, input.Location.Longitude)
	if err != nil {
		return false, handleError(ctx, err)
	}

	// Update location directly in repository (lightweight operation)
	err = r.Resolver.userService.UpdateLocation(ctx, userID, location.Latitude(), location.Longitude())
	if err != nil {
		return false, handleError(ctx, err)
	}

	return true, nil
}

// ApproveKyc approves captain KYC (admin only)
func (r *mutationResolver) ApproveKyc(ctx context.Context, captainID string, reason *string) (*model.User, error) {
	// Check if user is admin
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can approve KYC")
	}

	updatedUser, err := r.Resolver.userService.ApproveKYC(ctx, captainID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(updatedUser), nil
}

// RejectKyc rejects captain KYC (admin only)
func (r *mutationResolver) RejectKyc(ctx context.Context, captainID string, reason string) (*model.User, error) {
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can reject KYC")
	}

	updatedUser, err := r.Resolver.userService.RejectKYC(ctx, captainID, reason)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(updatedUser), nil
}

// BlockUser blocks a user account (admin only)
func (r *mutationResolver) BlockUser(ctx context.Context, userID string, reason string) (*model.User, error) {
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can block users")
	}

	updatedUser, err := r.Resolver.userService.BlockUser(ctx, userID, reason)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(updatedUser), nil
}

// UnblockUser unblocks a user account (admin only)
func (r *mutationResolver) UnblockUser(ctx context.Context, userID string) (*model.User, error) {
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can unblock users")
	}

	updatedUser, err := r.Resolver.userService.UnblockUser(ctx, userID)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(updatedUser), nil
}

// User returns user by ID
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.Resolver.userService.GetUser(ctx, id)
	if err != nil {
		if err == domain.ErrNotFound {
			return nil, nil
		}
		return nil, handleError(ctx, err)
	}

	return userToGraphQL(user), nil
}

// SearchUsers searches users (admin only)
func (r *queryResolver) SearchUsers(ctx context.Context, input model.UserSearchInput) (*model.UserConnection, error) {
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can search users")
	}

	query := stringValue(input.Query)
	role := ""
	if input.Role != nil {
		role = string(*input.Role)
	}

	limit := 20
	if input.Limit != nil {
		limit = *input.Limit
	}

	offset := 0
	if input.Offset != nil {
		offset = *input.Offset
	}

	users, total, err := r.Resolver.userService.SearchUsers(ctx, query, role, limit, offset)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	edges := make([]*model.UserEdge, len(users))
	for i, user := range users {
		edges[i] = &model.UserEdge{
			Cursor: fmt.Sprintf("%d", offset+i),
			Node:   userToGraphQL(user),
		}
	}

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     int64(offset+limit) < total,
			HasPreviousPage: offset > 0,
			Total:           int(total),
		},
		TotalCount: int(total),
	}, nil
}

// PendingKYCCaptains returns captains pending KYC (admin only)
func (r *queryResolver) PendingKYCCaptains(ctx context.Context, limit *int, offset *int) (*model.UserConnection, error) {
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can view pending KYC")
	}

	l := 20
	if limit != nil {
		l = *limit
	}

	o := 0
	if offset != nil {
		o = *offset
	}

	captains, err := r.Resolver.userService.FindCaptainsByStatus(ctx, "PENDING")
	if err != nil {
		return nil, handleError(ctx, err)
	}

	// Apply pagination
	start := o
	end := o + l
	if start > len(captains) {
		start = len(captains)
	}
	if end > len(captains) {
		end = len(captains)
	}

	paginatedCaptains := captains[start:end]

	edges := make([]*model.UserEdge, len(paginatedCaptains))
	for i, user := range paginatedCaptains {
		edges[i] = &model.UserEdge{
			Cursor: fmt.Sprintf("%d", o+i),
			Node:   userToGraphQL(user),
		}
	}

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     end < len(captains),
			HasPreviousPage: start > 0,
			Total:           len(captains),
		},
		TotalCount: len(captains),
	}, nil
}

// NearbyCaptains finds captains near a location
func (r *queryResolver) NearbyCaptains(ctx context.Context, latitude float64, longitude float64, radiusKm *float64) ([]*model.User, error) {
	radius := 5.0 // Default 5km
	if radiusKm != nil {
		radius = *radiusKm
	}

	captains, err := r.Resolver.userService.FindCaptainsNearby(ctx, latitude, longitude, radius)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	result := make([]*model.User, len(captains))
	for i, captain := range captains {
		result[i] = userToGraphQL(captain)
	}

	return result, nil
}

// UserStats returns user statistics (admin only)
func (r *queryResolver) UserStats(ctx context.Context) (*model.UserStats, error) {
	if !isAdmin(ctx) {
		return nil, pkgErrors.ErrForbidden("Only admins can view statistics")
	}

	stats, err := r.Resolver.userService.GetUserStats(ctx)
	if err != nil {
		return nil, handleError(ctx, err)
	}

	return &model.UserStats{
		TotalUsers:       int(stats.TotalUsers),
		TotalCustomers:   int(stats.TotalCustomers),
		TotalCaptains:    int(stats.TotalCaptains),
		TotalAdmins:      int(stats.TotalAdmins),
		ActiveUsers:      int(stats.ActiveUsers),
		VerifiedCaptains: int(stats.VerifiedCaptains),
		OnlineCaptains:   0, // TODO: Calculate from captain availability
	}, nil
}
