// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

// Input for adding phone to customer account
type AddPhoneInput struct {
	// Phone number to add
	Phone string `json:"phone"`
}

// Address represents a saved delivery address
// Includes ML-ready usage analytics for smart suggestions
type Address struct {
	// Unique address ID
	ID string `json:"id"`
	// User who owns this address
	UserID string `json:"userID"`
	// Address label (HOME, WORK, OTHER)
	Label AddressLabel `json:"label"`
	// Primary address line
	AddressLine1 string `json:"addressLine1"`
	// Secondary address line
	AddressLine2 *string `json:"addressLine2,omitempty"`
	// Landmark for easier location
	Landmark *string `json:"landmark,omitempty"`
	// City
	City string `json:"city"`
	// State/Province
	State string `json:"state"`
	// Country
	Country string `json:"country"`
	// Postal/ZIP code
	PostalCode *string `json:"postalCode,omitempty"`
	// GPS coordinates
	Location *Location `json:"location"`
	// Contact person name at this address
	ContactName *string `json:"contactName,omitempty"`
	// Contact phone at this address
	ContactPhone *string `json:"contactPhone,omitempty"`
	// Is this the default address?
	IsDefault bool `json:"isDefault"`
	// Is this address active?
	IsActive bool `json:"isActive"`
	// Has GPS location been verified?
	IsVerified bool `json:"isVerified"`
	// Total times this address has been used
	UsageCount int `json:"usageCount"`
	// Last time this address was used
	LastUsedAt *time.Time `json:"lastUsedAt,omitempty"`
	// Usage score (0-100) for ranking
	UsageScore float64 `json:"usageScore"`
	// Morning usage count (6 AM - 12 PM)
	MorningUsageCount int `json:"morningUsageCount"`
	// Afternoon usage count (12 PM - 6 PM)
	AfternoonUsageCount int `json:"afternoonUsageCount"`
	// Evening usage count (6 PM - 12 AM)
	EveningUsageCount int `json:"eveningUsageCount"`
	// Night usage count (12 AM - 6 AM)
	NightUsageCount int `json:"nightUsageCount"`
	// Weekday usage count
	WeekdayUsageCount int `json:"weekdayUsageCount"`
	// Weekend usage count
	WeekendUsageCount int `json:"weekendUsageCount"`
	// Is this likely a home address? (based on usage patterns)
	IsLikelyHome bool `json:"isLikelyHome"`
	// Is this likely a work address? (based on usage patterns)
	IsLikelyWork bool `json:"isLikelyWork"`
	// Preferred time slot for this address
	PreferredTimeSlot TimeOfDay `json:"preferredTimeSlot"`
	// Full formatted address
	FullAddress string `json:"fullAddress"`
	// Short address for display
	ShortAddress string `json:"shortAddress"`
	// Address creation time
	CreatedAt time.Time `json:"createdAt"`
	// Last update time
	UpdatedAt time.Time `json:"updatedAt"`
}

// AddressConnection for paginated address lists
type AddressConnection struct {
	Edges      []*AddressEdge `json:"edges"`
	PageInfo   *PageInfo      `json:"pageInfo"`
	TotalCount int            `json:"totalCount"`
}

// AddressEdge wraps address with cursor
type AddressEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Address `json:"node"`
}

// Input for searching addresses
type AddressSearchInput struct {
	// Search query (city, state, postal code)
	Query *string `json:"query,omitempty"`
	// Results per page
	Limit *int `json:"limit,omitempty"`
	// Page offset
	Offset *int `json:"offset,omitempty"`
}

// AddressStats provides address usage statistics
type AddressStats struct {
	// Total addresses
	TotalAddresses int `json:"totalAddresses"`
	// Default address
	DefaultAddress *Address `json:"defaultAddress,omitempty"`
	// Most used address
	MostUsedAddress *Address `json:"mostUsedAddress,omitempty"`
	// Recently used addresses
	RecentAddresses []*Address `json:"recentAddresses"`
}

// AddressSuggestion represents a smart address suggestion
type AddressSuggestion struct {
	// The suggested address
	Address *Address `json:"address"`
	// Suggestion score (0-100)
	Score float64 `json:"score"`
	// Reason for suggestion
	Reason string `json:"reason"`
}

// AdminProfile contains admin-specific information
type AdminProfile struct {
	// Admin permissions
	Permissions []string `json:"permissions"`
	// Department
	Department string `json:"department"`
	// Employee ID
	EmployeeID *string `json:"employeeID,omitempty"`
}

// AuthResponse returned after successful authentication
type AuthResponse struct {
	// Authentication tokens
	Tokens *AuthToken `json:"tokens"`
	// Authenticated user
	User *User `json:"user"`
	// Whether this is a new user
	IsNewUser bool `json:"isNewUser"`
	// Additional flags
	NeedsPhone *bool `json:"needsPhone,omitempty"`
	NeedsKyc   *bool `json:"needsKYC,omitempty"`
}

// AuthToken contains access and refresh tokens
type AuthToken struct {
	// Short-lived access token (15 minutes)
	AccessToken string `json:"accessToken"`
	// Long-lived refresh token (60 days)
	RefreshToken string `json:"refreshToken"`
	// Access token expiration time
	ExpiresAt time.Time `json:"expiresAt"`
	// Token type (always "Bearer")
	TokenType string `json:"tokenType"`
}

// Input for becoming a captain
type BecomeCaptainInput struct {
	// Phone number (if not already present)
	Phone *string `json:"phone,omitempty"`
}

// CaptainAvailability represents captain's online/offline status
type CaptainAvailability struct {
	// Captain ID
	CaptainID string `json:"captainID"`
	// Is captain available?
	IsAvailable bool `json:"isAvailable"`
	// Current location if available
	Location *Location `json:"location,omitempty"`
	// Timestamp of change
	Timestamp time.Time `json:"timestamp"`
}

// CaptainProfile contains captain-specific information
type CaptainProfile struct {
	// Vehicle type
	VehicleType *VehicleType `json:"vehicleType,omitempty"`
	// Vehicle registration number
	VehicleNumber *string `json:"vehicleNumber,omitempty"`
	// Vehicle model
	VehicleModel *string `json:"vehicleModel,omitempty"`
	// Driving license number
	LicenseNumber *string `json:"licenseNumber,omitempty"`
	// License expiry date
	LicenseExpiry *time.Time `json:"licenseExpiry,omitempty"`
	// KYC verification status
	KycStatus KYCStatus `json:"kycStatus"`
	// KYC documents
	KycDocuments []*KYCDocument `json:"kycDocuments,omitempty"`
	// Whether captain is currently available for orders
	IsAvailable bool `json:"isAvailable"`
	// Current location (if available)
	CurrentLocation *Location `json:"currentLocation,omitempty"`
	// Last location update time
	LocationUpdatedAt *time.Time `json:"locationUpdatedAt,omitempty"`
	// Order completion rate (0-100)
	CompletionRate float64 `json:"completionRate"`
	// Cancellation rate (0-100)
	CancellationRate float64 `json:"cancellationRate"`
	// On-time delivery rate (0-100)
	OnTimeRate float64 `json:"onTimeRate"`
	// Onboarding completion time
	OnboardedAt *time.Time `json:"onboardedAt,omitempty"`
	// KYC verification time
	VerifiedAt *time.Time `json:"verifiedAt,omitempty"`
}

// ContactInfo for non-user contacts (pickup/delivery persons)
type ContactInfo struct {
	Name           string `json:"name"`
	Phone          string `json:"phone"`
	FormattedPhone string `json:"formattedPhone"`
}

// Input for contact information
type ContactInfoInput struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
}

// Input for creating a new address
type CreateAddressInput struct {
	// Address label
	Label *AddressLabel `json:"label,omitempty"`
	// Primary address line
	AddressLine1 string `json:"addressLine1"`
	// Secondary address line
	AddressLine2 *string `json:"addressLine2,omitempty"`
	// Landmark
	Landmark *string `json:"landmark,omitempty"`
	// City
	City string `json:"city"`
	// State/Province
	State string `json:"state"`
	// Country
	Country *string `json:"country,omitempty"`
	// Postal/ZIP code
	PostalCode *string `json:"postalCode,omitempty"`
	// GPS location
	Location *LocationInput `json:"location"`
	// Contact person name
	ContactName *string `json:"contactName,omitempty"`
	// Contact phone
	ContactPhone *string `json:"contactPhone,omitempty"`
	// Set as default address
	SetAsDefault *bool `json:"setAsDefault,omitempty"`
}

// Error represents a structured error response
// Provides client-friendly error messages and codes
type Error struct {
	// Error code for programmatic handling
	Code string `json:"code"`
	// Human-readable error message
	Message string `json:"message"`
	// Optional field that caused the error
	Field *string `json:"field,omitempty"`
	// Additional error details
	Details map[string]any `json:"details,omitempty"`
}

// File represents an uploaded file
type File struct {
	// Unique file ID
	ID string `json:"id"`
	// Original filename
	Filename string `json:"filename"`
	// File MIME type
	Mimetype string `json:"mimetype"`
	// File size in bytes
	Size int `json:"size"`
	// URL to access the file
	URL string `json:"url"`
	// Upload timestamp
	UploadedAt time.Time `json:"uploadedAt"`
}

// Input for going online as captain
type GoOnlineInput struct {
	// Current location
	Location *LocationInput `json:"location"`
}

// KYC Document
type KYCDocument struct {
	// Document type
	Type string `json:"type"`
	// Document URL
	URL string `json:"url"`
	// Upload timestamp
	UploadedAt time.Time `json:"uploadedAt"`
}

// Location represents geographic coordinates
type Location struct {
	// Latitude (-90 to 90)
	Latitude float64 `json:"latitude"`
	// Longitude (-180 to 180)
	Longitude float64 `json:"longitude"`
	// Formatted address if available
	Address *string `json:"address,omitempty"`
}

// Input for location data
type LocationInput struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

// Money represents a monetary value with currency
// Always stored in smallest unit (paise for INR, cents for USD)
type Money struct {
	// Amount in smallest unit (e.g., paise, cents)
	Amount int `json:"amount"`
	// ISO 4217 currency code (e.g., INR, USD)
	Currency string `json:"currency"`
	// Amount in major unit for display (e.g., rupees, dollars)
	DisplayAmount float64 `json:"displayAmount"`
	// Formatted string for display (e.g., "₹50.99")
	Formatted string `json:"formatted"`
}

// Input for monetary values
type MoneyInput struct {
	// Amount in major unit (e.g., rupees, dollars)
	Amount float64 `json:"amount"`
	// ISO 4217 currency code
	Currency string `json:"currency"`
}

// Root Mutation type - all write operations
type Mutation struct {
}

// OTPResponse after requesting OTP
type OTPResponse struct {
	// Whether OTP was sent successfully
	Success bool `json:"success"`
	// Message for the user
	Message string `json:"message"`
	// Target (phone/email) where OTP was sent
	Target string `json:"target"`
	// OTP expiration time
	ExpiresAt time.Time `json:"expiresAt"`
	// Remaining attempts before rate limit
	RemainingAttempts *int `json:"remainingAttempts,omitempty"`
}

// PageInfo contains pagination metadata
type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
	Total           int     `json:"total"`
}

// Root Query type - all read operations
type Query struct {
}

// Input for refreshing access token
type RefreshTokenInput struct {
	// Refresh token
	RefreshToken string `json:"refreshToken"`
}

// Input for requesting OTP
type RequestOTPInput struct {
	// Phone number (international format)
	Phone string `json:"phone"`
	// Purpose of the OTP
	Purpose OTPPurpose `json:"purpose"`
}

// Session represents an active user session
type Session struct {
	// Session ID
	ID string `json:"id"`
	// Device type
	Device DeviceType `json:"device"`
	// Device information
	DeviceInfo map[string]any `json:"deviceInfo,omitempty"`
	// Last activity timestamp
	LastUsedAt time.Time `json:"lastUsedAt"`
	// Session creation time
	CreatedAt time.Time `json:"createdAt"`
	// Session expiration time
	ExpiresAt time.Time `json:"expiresAt"`
	// Whether session is currently active
	IsActive bool `json:"isActive"`
}

// Input for social login (Google/Apple)
type SocialLoginInput struct {
	// Provider (GOOGLE or APPLE)
	Provider AuthProvider `json:"provider"`
	// User ID from the provider
	ProviderID string `json:"providerID"`
	// Email address from provider
	Email string `json:"email"`
	// First name
	FirstName string `json:"firstName"`
	// Last name
	LastName string `json:"lastName"`
	// Profile picture URL
	ProfilePic *string `json:"profilePic,omitempty"`
	// Device type
	DeviceType DeviceType `json:"deviceType"`
	// Additional device information
	DeviceInfo map[string]any `json:"deviceInfo,omitempty"`
}

// Input for submitting KYC documents
type SubmitKYCInput struct {
	// Driving license image
	License graphql.Upload `json:"license"`
	// Vehicle RC image
	VehicleRc graphql.Upload `json:"vehicleRC"`
	// Profile photo
	ProfilePhoto graphql.Upload `json:"profilePhoto"`
	// Additional documents
	AdditionalDocs []*graphql.Upload `json:"additionalDocs,omitempty"`
}

// Root Subscription type - real-time updates
type Subscription struct {
}

// Input for updating an address
type UpdateAddressInput struct {
	// Address ID to update
	ID string `json:"id"`
	// Address label
	Label *AddressLabel `json:"label,omitempty"`
	// Primary address line
	AddressLine1 *string `json:"addressLine1,omitempty"`
	// Secondary address line
	AddressLine2 *string `json:"addressLine2,omitempty"`
	// Landmark
	Landmark *string `json:"landmark,omitempty"`
	// City
	City *string `json:"city,omitempty"`
	// State/Province
	State *string `json:"state,omitempty"`
	// Postal/ZIP code
	PostalCode *string `json:"postalCode,omitempty"`
	// GPS location
	Location *LocationInput `json:"location,omitempty"`
	// Contact person name
	ContactName *string `json:"contactName,omitempty"`
	// Contact phone
	ContactPhone *string `json:"contactPhone,omitempty"`
}

// Input for updating captain location
type UpdateLocationInput struct {
	// New location
	Location *LocationInput `json:"location"`
}

// Input for updating user profile
type UpdateProfileInput struct {
	// First name
	FirstName *string `json:"firstName,omitempty"`
	// Last name
	LastName *string `json:"lastName,omitempty"`
	// Profile picture
	ProfilePic *graphql.Upload `json:"profilePic,omitempty"`
}

// Input for updating vehicle information
type UpdateVehicleInput struct {
	// Vehicle type
	VehicleType VehicleType `json:"vehicleType"`
	// Vehicle registration number
	VehicleNumber string `json:"vehicleNumber"`
	// Vehicle model
	VehicleModel string `json:"vehicleModel"`
}

// User represents a registered user (Customer, Captain, or Admin)
// Supports dual-role: one user can be both Customer and Captain
type User struct {
	// Unique user ID
	ID string `json:"id"`
	// First name
	FirstName string `json:"firstName"`
	// Last name
	LastName string `json:"lastName"`
	// Full name (computed)
	FullName string `json:"fullName"`
	// Profile picture URL
	ProfilePic *string `json:"profilePic,omitempty"`
	// Email address
	Email *string `json:"email,omitempty"`
	// Email verification status
	EmailVerified bool `json:"emailVerified"`
	// Phone number
	Phone *string `json:"phone,omitempty"`
	// Phone verification status
	PhoneVerified bool `json:"phoneVerified"`
	// Primary role (initial role)
	PrimaryRole UserRole `json:"primaryRole"`
	// All roles user has
	Roles []UserRole `json:"roles"`
	// Account status
	Status UserStatus `json:"status"`
	// Wallet balance
	WalletBalance *Money `json:"walletBalance"`
	// Average rating (1-5)
	Rating *float64 `json:"rating,omitempty"`
	// Total number of ratings
	TotalRatings int `json:"totalRatings"`
	// Total orders placed (as customer)
	TotalOrders int `json:"totalOrders"`
	// Total deliveries completed (as captain)
	TotalDeliveries int `json:"totalDeliveries"`
	// Captain profile (only if user has CAPTAIN role)
	CaptainProfile *CaptainProfile `json:"captainProfile,omitempty"`
	// Admin profile (only if user has ADMIN role)
	AdminProfile *AdminProfile `json:"adminProfile,omitempty"`
	// Account creation time
	CreatedAt time.Time `json:"createdAt"`
	// Last update time
	UpdatedAt time.Time `json:"updatedAt"`
	// Last activity time
	LastActiveAt *time.Time `json:"lastActiveAt,omitempty"`
}

// UserConnection for paginated user lists
type UserConnection struct {
	Edges      []*UserEdge `json:"edges"`
	PageInfo   *PageInfo   `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

// UserEdge wraps user with cursor
type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node"`
}

// Input for user search
type UserSearchInput struct {
	// Search query (name, email, phone)
	Query *string `json:"query,omitempty"`
	// Filter by role
	Role *UserRole `json:"role,omitempty"`
	// Filter by status
	Status *UserStatus `json:"status,omitempty"`
	// Results per page
	Limit *int `json:"limit,omitempty"`
	// Page offset
	Offset *int `json:"offset,omitempty"`
}

// UserStats provides aggregated user statistics
type UserStats struct {
	// Total users
	TotalUsers int `json:"totalUsers"`
	// Total customers
	TotalCustomers int `json:"totalCustomers"`
	// Total captains
	TotalCaptains int `json:"totalCaptains"`
	// Total admins
	TotalAdmins int `json:"totalAdmins"`
	// Active users (last 7 days)
	ActiveUsers int `json:"activeUsers"`
	// Verified captains
	VerifiedCaptains int `json:"verifiedCaptains"`
	// Online captains
	OnlineCaptains int `json:"onlineCaptains"`
}

// ValidationError for input validation failures
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
	Code    string `json:"code"`
}

// Input for verifying OTP and logging in
type VerifyOTPInput struct {
	// Phone number
	Phone string `json:"phone"`
	// 6-digit OTP code
	Code string `json:"code"`
	// Purpose of verification
	Purpose OTPPurpose `json:"purpose"`
	// Device type
	DeviceType DeviceType `json:"deviceType"`
	// Additional device information
	DeviceInfo map[string]any `json:"deviceInfo,omitempty"`
}

// Input for verifying added phone
type VerifyPhoneInput struct {
	// Phone number
	Phone string `json:"phone"`
	// Verification code
	Code string `json:"code"`
}

// Address labels
type AddressLabel string

const (
	AddressLabelHome  AddressLabel = "HOME"
	AddressLabelWork  AddressLabel = "WORK"
	AddressLabelOther AddressLabel = "OTHER"
)

var AllAddressLabel = []AddressLabel{
	AddressLabelHome,
	AddressLabelWork,
	AddressLabelOther,
}

func (e AddressLabel) IsValid() bool {
	switch e {
	case AddressLabelHome, AddressLabelWork, AddressLabelOther:
		return true
	}
	return false
}

func (e AddressLabel) String() string {
	return string(e)
}

func (e *AddressLabel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AddressLabel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AddressLabel", str)
	}
	return nil
}

func (e AddressLabel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AddressLabel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AddressLabel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Social login providers
type AuthProvider string

const (
	AuthProviderGoogle AuthProvider = "GOOGLE"
	AuthProviderApple  AuthProvider = "APPLE"
	AuthProviderPhone  AuthProvider = "PHONE"
	AuthProviderEmail  AuthProvider = "EMAIL"
)

var AllAuthProvider = []AuthProvider{
	AuthProviderGoogle,
	AuthProviderApple,
	AuthProviderPhone,
	AuthProviderEmail,
}

func (e AuthProvider) IsValid() bool {
	switch e {
	case AuthProviderGoogle, AuthProviderApple, AuthProviderPhone, AuthProviderEmail:
		return true
	}
	return false
}

func (e AuthProvider) String() string {
	return string(e)
}

func (e *AuthProvider) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AuthProvider(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AuthProvider", str)
	}
	return nil
}

func (e AuthProvider) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AuthProvider) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AuthProvider) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Device type for authentication
type DeviceType string

const (
	DeviceTypeIos     DeviceType = "IOS"
	DeviceTypeAndroid DeviceType = "ANDROID"
	DeviceTypeWeb     DeviceType = "WEB"
)

var AllDeviceType = []DeviceType{
	DeviceTypeIos,
	DeviceTypeAndroid,
	DeviceTypeWeb,
}

func (e DeviceType) IsValid() bool {
	switch e {
	case DeviceTypeIos, DeviceTypeAndroid, DeviceTypeWeb:
		return true
	}
	return false
}

func (e DeviceType) String() string {
	return string(e)
}

func (e *DeviceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeviceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeviceType", str)
	}
	return nil
}

func (e DeviceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeviceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeviceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// KYC verification status
type KYCStatus string

const (
	KYCStatusPending  KYCStatus = "PENDING"
	KYCStatusVerified KYCStatus = "VERIFIED"
	KYCStatusRejected KYCStatus = "REJECTED"
)

var AllKYCStatus = []KYCStatus{
	KYCStatusPending,
	KYCStatusVerified,
	KYCStatusRejected,
}

func (e KYCStatus) IsValid() bool {
	switch e {
	case KYCStatusPending, KYCStatusVerified, KYCStatusRejected:
		return true
	}
	return false
}

func (e KYCStatus) String() string {
	return string(e)
}

func (e *KYCStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = KYCStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid KYCStatus", str)
	}
	return nil
}

func (e KYCStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *KYCStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e KYCStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// OTP purpose
type OTPPurpose string

const (
	OTPPurposeLogin         OTPPurpose = "LOGIN"
	OTPPurposeVerification  OTPPurpose = "VERIFICATION"
	OTPPurposePasswordReset OTPPurpose = "PASSWORD_RESET"
	OTPPurposeOrderPickup   OTPPurpose = "ORDER_PICKUP"
	OTPPurposeOrderDelivery OTPPurpose = "ORDER_DELIVERY"
)

var AllOTPPurpose = []OTPPurpose{
	OTPPurposeLogin,
	OTPPurposeVerification,
	OTPPurposePasswordReset,
	OTPPurposeOrderPickup,
	OTPPurposeOrderDelivery,
}

func (e OTPPurpose) IsValid() bool {
	switch e {
	case OTPPurposeLogin, OTPPurposeVerification, OTPPurposePasswordReset, OTPPurposeOrderPickup, OTPPurposeOrderDelivery:
		return true
	}
	return false
}

func (e OTPPurpose) String() string {
	return string(e)
}

func (e *OTPPurpose) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OTPPurpose(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OTPPurpose", str)
	}
	return nil
}

func (e OTPPurpose) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OTPPurpose) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OTPPurpose) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Sort order for lists
type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Status enum for various entities
type Status string

const (
	StatusActive    Status = "ACTIVE"
	StatusInactive  Status = "INACTIVE"
	StatusBlocked   Status = "BLOCKED"
	StatusSuspended Status = "SUSPENDED"
	StatusPending   Status = "PENDING"
	StatusDeleted   Status = "DELETED"
)

var AllStatus = []Status{
	StatusActive,
	StatusInactive,
	StatusBlocked,
	StatusSuspended,
	StatusPending,
	StatusDeleted,
}

func (e Status) IsValid() bool {
	switch e {
	case StatusActive, StatusInactive, StatusBlocked, StatusSuspended, StatusPending, StatusDeleted:
		return true
	}
	return false
}

func (e Status) String() string {
	return string(e)
}

func (e *Status) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Status(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Status", str)
	}
	return nil
}

func (e Status) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Status) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Status) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Time of day for analytics
type TimeOfDay string

const (
	TimeOfDayMorning   TimeOfDay = "MORNING"
	TimeOfDayAfternoon TimeOfDay = "AFTERNOON"
	TimeOfDayEvening   TimeOfDay = "EVENING"
	TimeOfDayNight     TimeOfDay = "NIGHT"
)

var AllTimeOfDay = []TimeOfDay{
	TimeOfDayMorning,
	TimeOfDayAfternoon,
	TimeOfDayEvening,
	TimeOfDayNight,
}

func (e TimeOfDay) IsValid() bool {
	switch e {
	case TimeOfDayMorning, TimeOfDayAfternoon, TimeOfDayEvening, TimeOfDayNight:
		return true
	}
	return false
}

func (e TimeOfDay) String() string {
	return string(e)
}

func (e *TimeOfDay) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TimeOfDay(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TimeOfDay", str)
	}
	return nil
}

func (e TimeOfDay) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TimeOfDay) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TimeOfDay) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// User roles
type UserRole string

const (
	UserRoleCustomer UserRole = "CUSTOMER"
	UserRoleCaptain  UserRole = "CAPTAIN"
	UserRoleAdmin    UserRole = "ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleCustomer,
	UserRoleCaptain,
	UserRoleAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleCustomer, UserRoleCaptain, UserRoleAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// User account status
type UserStatus string

const (
	UserStatusActive      UserStatus = "ACTIVE"
	UserStatusBlocked     UserStatus = "BLOCKED"
	UserStatusPendingKyc  UserStatus = "PENDING_KYC"
	UserStatusSuspended   UserStatus = "SUSPENDED"
	UserStatusDeactivated UserStatus = "DEACTIVATED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusBlocked,
	UserStatusPendingKyc,
	UserStatusSuspended,
	UserStatusDeactivated,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusBlocked, UserStatusPendingKyc, UserStatusSuspended, UserStatusDeactivated:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Vehicle types for captains
type VehicleType string

const (
	VehicleTypeBike  VehicleType = "BIKE"
	VehicleTypeCar   VehicleType = "CAR"
	VehicleTypeVan   VehicleType = "VAN"
	VehicleTypeTruck VehicleType = "TRUCK"
)

var AllVehicleType = []VehicleType{
	VehicleTypeBike,
	VehicleTypeCar,
	VehicleTypeVan,
	VehicleTypeTruck,
}

func (e VehicleType) IsValid() bool {
	switch e {
	case VehicleTypeBike, VehicleTypeCar, VehicleTypeVan, VehicleTypeTruck:
		return true
	}
	return false
}

func (e VehicleType) String() string {
	return string(e)
}

func (e *VehicleType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VehicleType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VehicleType", str)
	}
	return nil
}

func (e VehicleType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VehicleType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VehicleType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
